### ISSUE TITLE
Export all pages, not just those linked to with <a> tags

### ISSUE THREAD

**Issue by jordn** [sveltejs/sapper#1014]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: I'm always frustrated when [...]
When I export, I get the main index page and all the other pages linked to with <a> tags. This is explained in the [docs](https://sapper.svelte.dev/docs#How_it_works). However, my site has multiple pages that aren't directly linked to: 404 pages, pages shown after form submission etc. and these do not get exported. This means that parts of my site do not work when I host the static site on Netlify.

**Describe the solution you'd like**
I'd like the 'npm run export' call to export all the files possible, not just those that are crawl-able from the main entry point. Ideally this should be inferred automatically, but I'd be willing to provide a sitemap file or equivalent to specify.

**Describe alternatives you've considered**

**How important is this feature to you?**
Quite important. This is blocking a straight-forward process of serving this from Netlify (both Sapper and Netlify have been excellent otherwise). I'm now looking to whether I should change my host and serve a node app, or whether there's an alternative way to produce the static files I need.

**Comment by Conduitry** [comment]
Exporting all pages is not, in general, well-defined: page URLs can contain param slots, and we have no idea what those might be filled in with. The way we find this out is by looking at what they're actually filled in with when other pages link to them.

There is, however, an `--entry` option added by #825 that lets you specify multiple entry points to crawl from, which is essentially a sitemap file, except in command line arguments.

**Comment by logannc** [comment]
I would ask you to reconsider this issue for routes that *are* static. I'm presented with the option of creating something to duplicates sappers routing logic in order to build my build command `sapper export --entry / /foo/ /bar/ /blah/` which is error prone, tedious, and somewhat difficult, or some other hack to include links on the page that I don't want. 

In my case, I have a link that either points to a manage page or a login page based on whether or not the client is logged in. During SSR, we render the button but it doesn't link to either. So neither my manage or login page get included.

This would not be a substitute but it would at least make things easier: an `--entry-file` argument to let me point to a file instead of having space-separated arguments would also help. Files are easier to deal with than properly escaping bash arguments. Also, now the user has more visibility into exactly what is being exported and it can be checked in if its not autogenerated.

**Comment by logannc** [comment]
It seems that https://github.com/sveltejs/sapper/blob/f3e9fc48d281ff990458a4a537a50d59db105e37/src/core/create_manifest_data.ts#L7 should have all of the information necessary for export to export all static routes (by adding them as default entrypoints).

**Comment by logannc** [comment]
I'm going to take a look at making a PR for this.

**Comment by pngwn** [comment]
This feature would be confusing when it breaks, which would be frequently due it the issues mentioned above. There is already a way to do this and we don’t really want to support multiples ways of doing the same thing.

**Comment by logannc** [comment]
The only issue mentioned above is URLs with param slots, which I am not seeking to enable.

My preferred solution here is to augment the default implementation for `entryPoints` so it picks up all static routes, not just `/`. This is *more* consistent with what someone would expect given the behaviour of running sapper in dev or as your hosting service. It's like a 6 line change given that you already have the information available.

I *think* it passes tests but its complaining that I don't have chrome started so some don't run.

**Comment by pngwn** [comment]
But it would be impossible to opt out without adding API.

**Comment by logannc** [comment]
1. its far easier to add `--entry /` than `--entry $FOUND_ROUTES` so some bash build script.
2. we could keep the existing behaviour and add a flag `--find-static-entry-points` that adds to `--entry` by default or something. (this option obviously would need bikeshedding)

This is a massive win in ergonomics for exported projects. I'd argue that this SHOULD be the default anyway and that the existing behaviour is confusing.
