### ISSUE TITLE
Windows 404-folder

### ISSUE THREAD

**Issue by Olyno** [sveltejs/sapper#1017]
Hi,
Using the command ``yarn export`` with Sapper, I get this error:
https://paste.md-5.net/zaqilofexe.java
The ``yarn dev`` command works fine.
Here is my source code: https://github.com/Olyno/skript-website
Any idea of how I could fix that please?

**Comment by bwbroersma** [comment]
`yarn dev` didn't work for me (on linux) because the [`.env`](https://github.com/Olyno/skript-website/blob/9a1603999ffbdace19ade64a0e001e2d2befd3d1/.env) file with `BASE_NAME=skript-website`. This means the whole website runs under `/skript-website` and links to `/something` will result in 404 (since it's not relative under `/skript-website/`). I think the windows in ignoring the `.env`, so running the dev site straight on `/`, so you don't have the 404 problems in dev. In export you run it with a base path, so it will result in 404's. It seems that a combination of 404's, maybe in combination with the fact that [`<a href="/documentation" on:click|preventDefault `](https://github.com/Olyno/skript-website/blob/9a1603999ffbdace19ade64a0e001e2d2befd3d1/src/components/Navbar.svelte#L21) will be followed (change it to a span/div/button if it should not) and resulting in a 404, but some logic on windows is missing to create the directory anyway, and then the next (sub) link results in an error (BTW the documentation not having an index page).

So remove the prefix `/` from your [Nav.svelte](
https://github.com/Olyno/skript-website/blob/9a1603999ffbdace19ade64a0e001e2d2befd3d1/src/components/Navbar.svelte#L23), [the original sapper-template](https://github.com/sveltejs/sapper-template/blob/master/src/components/Nav.svelte#L54) uses relative url's.

Next: let's find that windows 404-folder not created but was expected anyway bug.

**Comment by Olyno** [comment]
Hi @bwbroersma,
Thanks a lot for your answer that solves my issue. You said it's still a valid issue as long as this one's a 404-folder error, so I'll let it open 😃
