### ISSUE TITLE
req.user is not saved in sapper.middleware

### ISSUE THREAD

**Issue by artur-sim** [sveltejs/sapper#1042]
Hi posted on github and on discord but did not get any reply for 2 days, so really need you help

```
app.use(
	cookieParser())
app.use(session({
	secret: 'sss',
	resave: true,
	saveUninitialized: true,
	// cookie: {
	// 	secure: true,
	// 	maxAge: 604800000,
	// },
	// store: new MongoDBStore({
	// 	uri: 'mongodb://127.0.0.1:27017/',
	// 	collection: 'mySessions'
	// })
}))
app.use(passport.initialize())
app.use(passport.session(), )
app.use(bodyParser.urlencoded({
	extended: true
}))
app.use(bodyParser.json())

app.post('/login', passport.authenticate('local'), (req, res, next) => {
	// if(req.user){
	// 	res.status(201).end();
	// }
	console.log('post')
	console.log(req.session.passport)
	console.log(req.user)
	console.log('--------------')
})
app.use(compression({
		threshold: 0
	}),
	sirv('static', {
		dev
	}),

	sapper.middleware({
		session: req => {
			console.log("req.user: " + req.user)
			console.log("req.session: " + req.session.passport)
			return {
				user: req.user || req.session.passport
			}
		}
	})

)
```

req.user is set but it is not available either before and after refresh on preload in store no where. Please tell me where im i doing mistake ?

**Comment by antony** [comment]
Hi @artur-sim 

I appreciate that you're not getting the help you need in discord, but github issues isn't the correct place to raise questions. Perhaps consider stackoverflow instead?

I will give you a pointer though. the `req` Sapper middleware gets isn't the `req` that express had. That's why your user is not there. You need to wrap the Sapper middleware. You can see an example of how I do this here: https://github.com/beyonk-adventures/sapper-rbac
