### ISSUE TITLE
Calling preload function not needed on export?

### ISSUE THREAD

**Issue by flohaider** [sveltejs/sapper#1065]
**Describe the bug**
When `sapper export` is used to generate a static site, the behaviour of pages having a `preload` function is inconsistent, depending on whether the page is fully loaded or it is loaded on client-side navigation.

**To Reproduce**
For example I have a page `index.svelte` in `src/routes/support`, which uses the preload function to do a simple GET request in order to retrieve a list of support articles from the Helpscout API:
```
<script context="module">
  export function preload({ params, query }) {
    return this.fetch('https://docsapi.helpscout.net/v1/collections/1234/articles')
      .then(r => r.json())
      .then(response => {
        return { articles: response.articles.items };
      });
  }
</script>
<script>
  export let articles;
</script>

<h1>Support Articles</h1>
<ul>
  {#each articles as article}
    <li><a href='support/{article.id}'>{article.name}</a></li>
  {/each}
</ul>
```
I then ran `sapper export` and opened the page in Chrome to inspect the requests being made in dev tools.

**Expected behavior**
When I open `localhost:5000` and then use a page link to navigate to `localhost:5000/support`, I can see there is still a request being made to `https://docsapi.helpscout.net/v1/collections/1234/articles`.
On the other hand, the API request is not made when I head directly to `localhost:5000/support`.

So it looks like the `preload` function is not called on full page loads, but only on navigation. Why is it called at all when `sapper export` is used? All data from the API is already there in static HTML, so I think this call is not needed.

**Comment by kevmodrome** [comment]
A workaround to this is to create an `index.json.js` file that does all the remote fetching in the support folder, the route will then be crawled and created locally. And in your client route component you use the preload to fetch from this route.

**Comment by Conduitry** [comment]
This is all working as expected. In a regular built (non-exported) Sapper site, `preload` is run on the server for initial server-rendered requests, and is run on the client for subsequent client-side navigation.

In the exported version, Sapper simpler crawls the server-rendered site, saving each page, and also saving each _local_ file requested by a `preload`. We don't want to have to worry about saving remote requests to local files and rewriting the remote URLs that are passed to `this.fetch` to point to the corresponding local files.

If you want a given remote request to be made anew each time a page is loaded (SSR or client-rendered) for an exported site, don't do it in `preload` and instead do it in an `onMount` or an `if (process.browser)`.

If you want the remote request's response to be baked into the exported site, make a local endpoint that proxies to the remote endpoint, and request that in your `preload`, so that its response will get saved during export.

**Comment by flohaider** [comment]
Thank you both for the quick response! Moving the API fetch to a local proxy solved this for me.
