### ISSUE TITLE
/index.html doesn't contain any <script>, breaks ServiceWorker

### ISSUE THREAD

**Issue by nolanlawson** [sveltejs/sapper#108]
Steps to repro:

```bash
git clone https://github.com/sveltejs/sapper-template # commit 9c3c45a as of today
cd sapper-template
npm i
npm run build
npm start
curl -sL 'http://localhost:3000/index.html' # doesn't contain any <script>s
```

It seems `localhost:3000/` contains the correct `<script>`, but `localhost:3000/index.html` does not. Unfortunately this means the ServiceWorker caches the incorrect `index.html` file, and thus the app breaks when you reload it.

**Comment by EmilTholin** [comment]
Hi @nolanlawson! Could it be because `/index.html` [has its own asset handler](https://github.com/sveltejs/sapper/blob/master/lib/index.js#L79-L84), which just serves the client index file from the asset cache, which is [the `200` page rendered without the scripts](https://github.com/sveltejs/sapper/blob/master/lib/utils/generate_asset_cache.js#L71-L76)?
`/` will however be handled by the [route handler](https://github.com/sveltejs/sapper/blob/master/lib/index.js#L57), which does [respond with the scripts](https://github.com/sveltejs/sapper/blob/master/lib/index.js#L153-L175).

**Comment by nolanlawson** [comment]
I resolved this manually with the following changes to `app/service-worker.js`:

```js
const toCache = shell.concat(assets)
  .concat(['/']) // fetch the home page and cache it immediately
```

And then:

```js
if (url.origin === self.origin && 
    routes.find(route => route.pattern.test(url.pathname))) {
  return caches.match('/')
}
```

Whether this should be added to `sapper-template` is up for grabs. But I think at best [this comment](https://github.com/sveltejs/sapper-template/blob/99445fa62b6b8f77a2ae7f6c7156923281144b3d/app/service-worker.js#L49-L57) is misleading and should maybe be removed. If you uncomment it, it doesn't actually work. (But the above modifications do.)

**Comment by nolanlawson** [comment]
I have taken another look at this issue. Now the issue is that neither `sapper build` nor `sapper export` actually creates an `index.html` file, so it 404s. That means that [this comment](https://github.com/sveltejs/sapper-template/blob/f71093805dae9ff534c8955b7b49ed69cefca717/app/service-worker.js#L51-L59) is still misleading, as uncommenting that block of code results in a broken app because the Service Worker can't actually serve a shell `index.html` file.

I'll keep looking into this, but it probably needs a new issue since this issue doesn't describe the problem.
