### ISSUE TITLE
more about persistence (server sessions and local storage)

### ISSUE THREAD

**Issue by hefeust** [sveltejs/sapper#1163]
Could the Sapper team produce a bit more of documentation about data persistence between pages ?

My use case are, given some routes:

     src/
      routes/
        index.svelte
        game.svelte
       help.svelte
       wizard_page_1.svelte
       wizard_page_2.svelte

I need to be able to:

* navigate to pages of wizard, and keep track of user choices before starting game
* during game, navigate to help page and back to game (at the same state)

some wizard options: { players_count: 3 , prefill_board: true , user_nickname: 'Bob', game_room_key: '981ms2'} and some other more...

the game state itself, is serializable as JSON.

I'm here since I think that help on how to integrate properly local storage and servers sessions while using Sapper could be useful for many people.

[in particular: correct use of *devalue*]
Thanks for help.

**Comment by antony** [comment]
The way you store data between pages and in the session with Sapper is using Stores.

The stores are documented here https://svelte.dev/tutorial/writable-stores and specific stores for Sapper for the session are documented here https://sapper.svelte.dev/docs#Stores

If you want to use localstorage to store data, you can write a custom store - there are a few examples on Google and StackOverflow. I don't think it's something want to explicitly document at this time as it's more of an advanced use of stores.

**Comment by nltesown** [comment]
I agree with @hefeust that better documentation and some examples would be very useful.

Client-side state persistence between Sapper pages is a very common use case but not so straightforward to implement (which  makes sense if it requires an "advanced use of stores"). I've tried to find some examples. https://chasingcode.dev/blog/svelte-persist-state-to-localstorage/ seems to do what @antony suggests (using a custom store) but doesn't work in Sapper because localStorage doesn't exist on the server, where the script is run first. Can Sapper's `session` store be used here, although we're not persisting data on the server? I find this confusing.

More generally, it would be helpful to clarify the relationship between Svelte stores and the `stores()` function from @sapper/app.

**Comment by MirrorBytes** [comment]
I'd like to ask why a check is not possible on the server like it would be for other frameworks? E.g.: ```if (localStorage) {}```
Wouldn't those kinds of edge cases be safe for SSR?

I use a function with Svelte projects that need persistence:

```typescript
import { writable } from 'svelte/store';
import type { Writable } from 'svelte/store';

export type JsonPrim = string | number | boolean | JsonPrim[] | null | undefined;
export type IndexableJsonValue = {
    [K in string | number]: IndexableJsonValue | IndexableJsonValue[] | JsonPrim;
};

export function local<T extends IndexableJsonValue>(
  key: string,
  initial: T,
): Writable<T> {
  const toString = (value: T) => JSON.stringify(value, null, 2); // helper function
  const toObj = JSON.parse; // helper function

  if (localStorage) {
    if (localStorage.getItem(key) === null) {
      localStorage.setItem(key, toString(initial));
    }

    const saved: T = toObj(localStorage.getItem(key) || '');

    const store = writable<T>(saved);

    return {
      subscribe: store.subscribe,
      set: (value: T) => {
        localStorage.setItem(key, toString(value));

        store.set(value);
      },
      update: (fn: (value: T) => T) => {
        store.update((val: T) => {
          const newVal = fn(val);

          localStorage.setItem(key, toString(newVal));

          return newVal;
        });
      },
    };
  }

  return writable(initial);
}
```

Theoretically, this should work (and does in other SSR implementations) with Sapper due to the check.
