### ISSUE TITLE
Sapper loads css and js files with 302 text-plain/html on express middleware res.redirect

### ISSUE THREAD

**Issue by weewex** [sveltejs/sapper#1166]
How can i make redirects from express middleware?

If i do res.redirect(302, "somepath") the page loads without style and js, because js and css files are loaded with 302 http response code and mime-type of text-plain/html.

Is there any other way than making a script for this on every page?

**Comment by Conduitry** [comment]
Do you have a repro? Is the issue just that your `res.redirect` is running before Sapper has a chance to serve its js or css on later requests?

**Comment by weewex** [comment]
I have a middleware in express app that runs before sapper middleware. In this middleware i do a `res.redirect` which gets called when a certain condition is met and must work on every page. For what i understand the req flow is that the `res.redirect` stops the flow the browser redirects you to that page and the req flow goes from start reaching `sapper.middleware`. In my case is that `sapper.middleware` handles the request correctly but the service worker loads any page specific js and css with the same `302 status code` and `mime text/html`. 

I don't know if thats intended or not. I would suggest that the service worker would handle such scenario properly OR making a function inside `sapper.middleware` that gets called on every request.

Sample code to better understand the problem:
server.js
`
express() // You can also use Express
	.use(
		(req,res,next) => {
			if(someConditionIsMet)
				res.redirect(302, 'somePath')
			
		},
		sapper.middleware({})
	)
	.listen(PORT, err => {
		if (err) console.error('error', err);
	});
`

**Comment by antony** [comment]
@weewex can you produce a small reproduction project showing this?

**Comment by Conduitry** [comment]
Looking at the above example, it does indeed sound like the issue is that you're also redirecting the `/client/` files that Sapper needs. _Maybe_ eventually we could reorganize how this works so that Sapper serves its static `/client/` stuff and its dynamic stuff from separate middleware - so that you can more easily insert your custom middleware in between the two - but for now, you just need to make sure that the `if (someConditionIsMet)` only applies to the paths you want it to.
