### ISSUE TITLE
Font-face not working

### ISSUE THREAD

**Issue by mlusca** [sveltejs/sapper#1167]
Font-face not woking a custom font on sapper?
Font is loaded, but not show..

`@font-face {
        font-family: Baske;
        src: url("fonts/BASKE1.ttf") format('truetype');
    }

    body {
        font-family: Baske, Arial !important;
    }`

**Comment by Conduitry** [comment]
Please follow the issue template and provide a repro.

**Comment by freethebit** [comment]
Just a comment on that, to help anyone that got stuck (me) trying to figure out how to use locally hosted fonts. 

In the context of `@font-face` in an css, scss, sass file. Toke me a while to figure out that in the `src: url()`: `fonts/` or `./fonts/` will not work because it will be resolved relative to `client.js` and not to `static` folder defined in `server.js`. To make it work just do `/fonts/` and it will be resolved to the `static` folder.
- :thumbsdown: `./path/to/myfont`
- :thumbsdown: `path/to/myfont`
- :thumbsup: `/path/to/myfont`

**Comment by rchrdnsh** [comment]
Thank you for this...got bit by the same issue in a sapper app, but `/path/to/myfont` fixed it! Yay!
