### ISSUE TITLE
deno

### ISSUE THREAD

**Issue by pjebs** [sveltejs/sapper#1201]
Is there anyway to get sapper to work with deno instead of node.js?

Deno is created by the original creator of node.js. It's his version of an improved node.js (if he could rebuild it from scratch).

https://github.com/denoland/deno

**Comment by antony** [comment]
Please search closed issues before opening new ones. We don't have the resource (or desire) to maintain a deno fork as well as a node one.

**Comment by shouze** [comment]
@antony so what's up about the desire since [deno is now a company](https://deno.com/blog/the-deno-company) and deno got more mature (1.8.2)?

We've seen emerging the deno nextjs thing akka [alephjs](https://alephjs.org/docs), is there a room for a deno sapper? In terms of developper experience I guess it would be great of course.
