### ISSUE TITLE
Issues with 'require' in .svelte files

### ISSUE THREAD

**Issue by StartMeUpLille** [sveltejs/sapper#1205]
**Describe the bug**
Problems with commonjs 'require'

Issue 1. Other imports/libraries stop working when ```const fs = require('fs');``` is enabled
In src/routes/index.svelte: when ```const fs = require('fs');``` is enabled inside the <script></script> tags, svelte-simple-modal stops working. Same issue with other plugings like micromodal
Also it doesn't accept ```import fs from 'fs'```

Issue 2. Impossible to require a file that exports variables
Error: Cannot find module '../data/exportvariable'

**Logs**
Issue 1. other imports/libraries stop working
Issue 2. Error: Cannot find module '../data/exportvariable'

**To Reproduce**
https://github.com/StartMeUpLille/sapper-require-issue

**Expected behavior**
I'd like 'require' to work as expected, as it seems to work ok in .js files, but becomes a problem in .svelte files

**Information about your Sapper Installation:**
- Your browser and the version: Chrome 81.0.4044.138

- Your operating system: Windows 10

- Your hosting environment: local

- Sapper version "0.27.13"

- Svelte version "3.22.2"

- application uses  Rollup

- Node version 12.16.3

**Severity**
Problematic for me, it makes my app project unusable

**Additional context**
Hi guys, I'm a bit of newbie in js and all the frameworks but I really don't see where I could get it wrong here. I'm not sure wether it'a sapper or svelte or rollup issue, sorry if I posted in the wrong place. The issues do not occur in normal js files. It occurs in the script tages of .svelte files.

Thanks for your help

**Comment by antony** [comment]
@StartMeUpLille you can't import `fs` into a script block. because a script block is run on both the server and client side. Whilst `fs` is available on the server-side, because it is a node-built-in, it isn't available on the client side, because the browser has no access to the user's filesystem.

You can only therefore use `fs` where the environment is node, which means either:

1. Using it only in [Server Routes](https://sapper.svelte.dev/docs#Server_routes)
2. Wrapping your import in `if (!process.browser) { }` which I wouldn't recommend, since you're probably doing something the wrong way here.

Please come and [chat to us](https://svelte.dev/chat) so we can discuss what you intend to do, and see if there is a better way of doing it.

**Comment by StartMeUpLille** [comment]
Many thanks @antony . 
Best regards
