### ISSUE TITLE
What is the preferred method to ensure props update on page navigation?

### ISSUE THREAD

**Issue by nealalpert** [sveltejs/sapper#1238]
Are we supposed to be using reactive statements to ensure pass by reference props are updated properly when a `[DynamicRoute]/index.svelte` page routes to the same page but with a different dynamic route variable?

Our use case: we have a product listing page with a component that takes an object as its only property.  When navigating to another product listing page we’ve noticed that these pass by reference props don’t seem to rehydrate with the new data returned from the server route as we expected.

Are reactive statements in the component the answer to this issue or is there another solution that the community prefers?

**Comment by antony** [comment]
@nealalpert Support questions are better asked in [Chat](https://svelte.dev/chat)

**Comment by khrome83** [comment]
@antony - so we close this issue and ask the question in Discord, the chat where no one responds, and it does not show on SEO? That is the preferrer way to handle this even though "Questions and Help" is one of the templates when posting an issue? 

Seeing as how we have built a production application of 70k pages using a framework that is basically vaporware. We have contributed multiple MRs that have been ignored, that sadly fix critical bugs. And when we ask a simple question, you use your limited time to close the issue than actually answer it. The least you could of done was see that we had ALREADY posted it in Discord and answered it there even. I just gotta say this is not the best way to run an open-source community. I am very disappointed. 

Ohh, and since your contributions to Sapper itself is basically limited to that specific template, I kind of thought you would know better.

Either reopen and let someone that knows the answer, answer. Or participate in Discord and actually answer the question there.

**Comment by antony** [comment]
@khrome83 I wasn't going to bother replying to this, as I find it extremely rude. As somebody who also runs large Sapper applications in production, I use my volunteered free time as I see fit.

I apologise that we haven't yet had the resource to review and merge your generous contributions, but I can assure you that they will be considered and merged as time allows. Support will continue to be provided to deserving users in the #support channel on discord, again, as time allows.

The "questions and help" template for issues on github, you will notice, says "go to discord for support, support issues opened on github will be closed". We do what we say on the tin.

I've not seen the open-source community that you run, but if you'd be kind enough to point me to it, I'll use it as a base from which to learn how to contribute to this one.

**Comment by khrome83** [comment]
@antony - I didn't read the template, just saw one exists. I am sorry, this was uncalled for. We were active in this project last year, with zero support. Our MRs have been sitting stale for almost a year now. I am happy to see you are trying to help manage the community. I owe you an apology. 

I am just jaded because our experience so far has been lackluster. Sapper has potential but has not seen a meaningful release in almost a year. Somehow the number of people exploring it is not dissuaded by the lack of activity and support. 

One of our MRs that fix critical memory leaks on export for example is just ignored. We are happy to participate and help, but to say "deserving users" has been the basic issue so far as I can tell.  The team has been slow to grow the core. I am happy to see that you were added. 

We have asked for guidance to get issues considered, looked at, or even feedback. Without a roadmap or any activity, as far as we can tell the project is dead and everyone is just being ignored. We have to maintain a fork just to unblock our efforts. And we have been thoughtful in trying to get any enhancements added in a backward-compatible way so they can one day be merged in. But once again, silence in all communication. 

The laughing emoji is the most response I have seen from @Conduitry no matter how many times we have reached out on Discord or Github issue MR.

**Comment by antony** [comment]
Hi @khrome83 that's ok - apology accepted.

I can completely understand your frustration, as I have been in the same place myself. I can only say that the features I hoped for over the years finally got merged in, but it was a waiting game, and I did end up running off my own fork for a short while.

Please allow me to apologise for the lack of communication around your PRs. We do genuinely appreciate the contributions, and we will merge them as soon as we are able, however the team of core maintainers is vastly under-resourced as we all have full time jobs and situations, that somehow, became even more demanding of our time during covid.

We're absolutely not ignoring PRs, but there is a significant amount of effort and thought that needs to go into every merge and feature add, which means that the rate at which we can merge them can seem slow. It's a tough balance.

I personally don't tend to merge things into core, because I'm certainly not at the level where I can truly appreciate all of the things which need to be considered in order to do so, but I can "proof read" and vet PRs, which I attempt to do when I have some spare time.

Also please don't mistake our time spent closing issues / chatting on discord to be time where we're not merging PRs, it's a completely different head-space. Trying to keep on top of what does and what doesn't belong in github issues is part of the process of getting things into an order whereby things can be addressed. If immediate answers aren't given on discord (due to lack of context / time / sleep), then StackOverflow is another good place to get answers.

So, I don't have any definitives for you or answers, certainly, but all I can say is that we will do our best to get your MRs merged as promptly as possible, and I hope that we can grow our core team over time to spread the load a bit, too.
