### ISSUE TITLE
Add protocol to page store

### ISSUE THREAD

**Issue by webfrank** [sveltejs/sapper#1287]
**Is your feature request related to a problem? Please describe.**
It would be useful to have access to protocol used to access page to dynamically build url like $page.protocol+'//'+$page.host

**Describe the solution you'd like**
Add protocol to page store

**Describe alternatives you've considered**
It could be used location.protocol but should be escaper for SSR

**How important is this feature to you?**
Not blocking but usefull

**Comment by PatrickG** [comment]
You can use `//` instead of the protocol, that will use the current protocol.

Example: `<a href="//other-domain.same-proto.col">...</a>`

**Comment by Conduitry** [comment]
This isn't something that there's really a general way to know during SSR. The default Sapper template only serves over HTTP, and the intention is that you'd have some sort of proxy in front of it handling the HTTPS. There's not a guaranteed way to know where the request originally came from.

If you want to do something like redirecting from HTTP to HTTPS (so that you can then always be certain that you're at an https:// URL) that should happen at a layer on top of Sapper.

If for some reason you need to serve content over both and are handling HTTPS via a proxy on top of Sapper, check what headers that adds that might tell you whether the original request was over HTTP or HTTPS and use that, for example, to populate a value in the session store.

If you need to serve content over both HTTP and HTTPS and you are handling HTTPS via a second server running in Node (which is not recommended), I believe there is a flag on the `IncomingMessage` or `ServerResponse` instance that you can use to check this and which can be used to populate a value in the session store.

**Comment by thgh** [comment]
I tend to configure an `ORIGIN` env variable which can be used in SSR.
