### ISSUE TITLE
feat: Add some focus management to components. 

### ISSUE THREAD

**Issue by ddaza** [sveltejs/sapper#1298]
**Is your feature request related to a problem? Please describe.**
I miss the days when you could just wait for `ready()` and call focus on components.
Coming from the React world I feel like that it a much-needed feature, specially if your App uses Modals or notifications to bring attention to the user and put them back where they were. This is specially important if you're trying to build a11y sites.

React handles this by passing `refs` basically DOM element references where you can call `focus()` when needed. It would be cool to have some solution in Svelte that would be a little more advanced than calling `document.querySelector` 

**Describe the solution you'd like**
Maybe a store queue that kept track of things like where your focus is and was so you can go back to the previously focused element (i.e. A modal that has steps A->B->C and when dismissed would go back to the original button)

**Describe alternatives you've considered**
Just using DOM selectors I suppose, but it could get confusing and have to add `setTimeOuts` for competing focus race conditions. 

**How important is this feature to you?**
This is super important for a11y applications. When you use a screen reader and lose the focus of the page after a modal often it will putt you at the top of the page. 
Imagine having to tab and listen to the whole page just to open a Modal or have a notification. 

**Additional context**
n/a

**Comment by benmccann** [comment]
For Sapper, I'm not sure it makes sense to add anything like a focus queue because most users won't need that in their application and we wouldn't want to ship that to the browser for every user of a Sapper application. If it can be handled in a more general way like a third-party library that users can choose to use or not use that would be better

Focus handling in general seems to be better discussed in the Svelte Discord. There's some discussion of handling focus on StackOverflow:

https://stackoverflow.com/questions/57257499/how-to-focus-on-newly-added-inputs-in-svelte
https://stackoverflow.com/questions/57354001/how-to-focus-on-input-field-loaded-from-component-in-svelte

**Comment by ddaza** [comment]
Oops, I meant to add this issue into the svelte repo instead of Sapper. 
The sentiment is the same tho. 
As Apps grow the focus management grows out of control if you don't have a system in place.
It would be nice to see maybe a library that achieves this. 
Regardless, thanks for the quick response.
