### ISSUE TITLE
Incorrect static links to slugs will cause slugs to not be generated at all.

### ISSUE THREAD

**Issue by StuartKent17** [sveltejs/sapper#1313]
**Describe the bug**
The crawling used on export will 404 slugs with malformed static URLS, meaning the website works well on 

**Logs**
```
> Built in 19.7s
> Crawling http://localhost:3001/subfolder/
   1.83 kB   index.html
   1.42 kB   service-worker-index.html
       9 B   (404) blog/what-is-sapper
     319 B   blog.json
   2.22 kB   blog/index.html
   1.54 kB   about/index.html
```

**To Reproduce**
Change Server.js / Package.json to serve the site from a subfolder, run dev and the blog page will still be present. Export and you will see the above. 

Repo / Commit with changed files / Example:
https://github.com/StuartKent17/sapper-bug/commit/387e23a8d1631ce97eec0bb73136abeb27309cf8

**Expected behavior**
A warning or error that a similar conflicting URL was discovered, instead of silently taking the first encountered.

**Severity**
Annoyance / Rough edge that has no real help online. This was the closest that helped me learn where to look for the problem. https://stackoverflow.com/questions/58501974/failing-to-generate-dynamic-routes-with-sapper-export

**Comment by Conduitry** [comment]
I'm not sure what you're saying should be changed? Is it incorrect that the links are 404s? Are you saying that exporting should complain more loudly when it runs across a link that's a 404? Something else?

**Comment by StuartKent17** [comment]
I believe that a static, incorrect and similar link on the homepage should
not cause the automatically generated and correctly set up links on the
blog page to break only on exporting. Having no knowledge of the code base
I feel like it might be a string comparison issue?

It just took a lot of figuring out to learn how the export actually worked,
generation from crawling makes sense but it's definitely counter intuitive.

"Error 404 crawling href '/blog/post name' in index.svelte line 53" would
provide context, aid understanding and not rely on a newbie realising the
order of generation matters.

The framework has been fantastic to work with.
Thanks for replying.

**Comment by antony** [comment]
Reading between the lines I gather that you actually want context of where each crawled link was originally found, in order to make tracing of where you've incorrectly given relative / non-relative links (or other issues with links) easier to spot.

I think the problem with this is that links that are crawled are a rendered concern rather than something which is detected prior to rendering, so the context of where the link was found to be crawled would actually reference an html file (and probably not a line number), and due to the dynamic nature of sites, even if it had a line number, or file, there's no guarantee that it would make anything easier to trace.

I think fundamentally, (404) tells you that a link isn't found and as a site author, if you don't know where that link occurs, or be able to figure it out fairly quickly, then you might have bigger problems.

I'd say that this is potentially something that could be improved (in some way), but I'd say that it's not something we'd be likely to spend time on in the near future, so in lieu of a pull request or a clear path to improvement, I'm inclined to close it.

Feel free to clarify anything if you strongly disagree.
