### ISSUE TITLE
Ability to routes to ignore directory, but not its content

### ISSUE THREAD

**Issue by ssrjs** [sveltejs/sapper#1330]
Inside `/routes/` I have a folder `/auth/` with `login.svelte`, `signup.svelte` + 5 other auth components
Also I have a folder `/documents/` with `terms-of-use.svelte`, `privacy-policy.svelte`, etc

I want all of them to be available without `/auth/` and `/documents/` respectively in url for "marketing" needs
But placing all of them to a root of `/routes/` will lead to complete disorder one day

There is a way to add underscore `/_auth/` to ignore full folder, but it will be awesome to ignore folder, but not its content

Did not think much about it, but maybe it can be reversed, something like: `/auth_`?

What do you think?

**Comment by antony** [comment]
Sapper has a file based router, so files are available where they are located on the filesystem. There are no plans or desire to change this.

You have a few options:

1. Make your routes into components, and have routes where you need them, which just load the components (this is what I do)
2. Add express-style route mappings into the `server.js` file
3. Use server routes and redirect to the desired content location
4. Use rewrites on http server (nginx, vercel etc)
5. Don't use Sapper, and use your own non file-based router, since Sapper is nearly 1/3rd the router.
