### ISSUE TITLE
TypeScript: sapper dev crashes on syntax errors

### ISSUE THREAD

**Issue by plashenkov** [sveltejs/sapper#1375]
As @benmccann noted in his comment https://github.com/sveltejs/sapper/issues/760#issuecomment-670698436 it's better to report TypeScript-related bugs as a new issues, so...

I've found that when using TypeScript with Sapper, `sapper dev` crashes when some mistakes/errors appear in source files.
It works correctly in JS mode.

Here is the example: https://take.ms/i9Ntm
(this example is taken from this template: https://github.com/babichjacob/sapper-typescript-graphql-template)

**Comment by nikibreg** [comment]
I think that's generally the expected behaviour of TypeScript.

**Comment by plashenkov** [comment]
It's okay for TypeScript transpiler to "crash" on syntax errors. As well as ES* transpiler. But dev server shouldn't crash when you do some accidental mistakes. It's developer unfriendly. You just type something incorrect, then your IDE or editor autosaves this, and dev server crashes, and you have to manually restart it. That's not OK.

**Comment by benmccann** [comment]
Thanks for taking the time to file this and providing a way to reproduce. I took a look at this and it also happens with https://github.com/sveltejs/template after running `node scripts/setupTypeScript.js`. Please file this as a bug over in https://github.com/rollup/plugins against `@rollup/plugin-typescript`. (It'd be better to use https://github.com/sveltejs/template than https://github.com/babichjacob/sapper-typescript-graphql-template when filing there since it's a vanilla Rollup project whereas Sapper's setup is quite unusual)

**Comment by benmccann** [comment]
I've done ahead and filed an issue over in the plugin repo: https://github.com/rollup/plugins/issues/542

**Comment by plashenkov** [comment]
Great, thank you!
