### ISSUE TITLE
sapper@0.28.0 generates 2 css files with identical content

### ISSUE THREAD

**Issue by Ashot-KR** [sveltejs/sapper#1397]
**Describe the bug**
In `0.28.0` sapper generates files `main.[hash].css` and `client.[hash].css` with identical content.

**To Reproduce**
Create new sapper project from template
```
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
npm install
```
Start app `npm run dev`
Open http://localhost:3000 in browser, open browser devtools on network/css
![Screenshot 2020-08-12 at 14 34 18](https://user-images.githubusercontent.com/899218/90011307-0b476200-dcaa-11ea-9c65-6ac477cedef6.png)
`main.[hash].css` and `client.[hash].css` has identical content.

This is css files generated with `sapper@0.27.16` and `rollup@2.23.1` (**UPD: added rollup version**)
![Screenshot 2020-08-12 at 14 33 21](https://user-images.githubusercontent.com/899218/90011461-4c3f7680-dcaa-11ea-893a-3a7b263d3cb9.png)

**Information about your Sapper Installation:**

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 615.80 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    rollup: ^2.3.4 => 2.23.1
    sapper: ^0.28.0 => 0.28.0
    svelte: ^3.17.3 => 3.24.1
```

**Comment by Ashot-KR** [comment]
Screenshot of styles from inspector:
![image](https://user-images.githubusercontent.com/899218/90011798-e69fba00-dcaa-11ea-95e4-be2754279b62.png)

**Comment by habibrosyad** [comment]
@Ashot-KR, what's your Rollup version with sapper v0.27.16?
If you're using Rollup v2, there was an issue here https://github.com/sveltejs/sapper-template/issues/233 which was solved with the release of v0.28.

**Comment by Ashot-KR** [comment]
@habibrosyad `rollup@2.23.1`

**Comment by habibrosyad** [comment]
Could you try downgrade your rollup version to `^1.20.0` and verify the generated CSSes? I suppose it should be identical with what you have with the current template now (sapper 0.28).

In https://github.com/sveltejs/sapper-template/issues/233, prior to the template upgrade using Rollup v2, sapper generated multiple chunks of CSS instead of just one like in your screenshot for v0.27. It was a bug because of breaking changes in Rollup 2 (https://github.com/rollup/rollup/issues/3655) which changed sapper's behaviour in outputting CSS. However I haven't confirmed whether between those chunks would have identical contents or not yet.

**Comment by Ashot-KR** [comment]
@habibrosyad btw, with `sapper@0.27.16` and `rollup@2.23.1` there is no such files (screenshot 2 in issue description)

**Comment by habibrosyad** [comment]
Yeah, that's what I mean, the behaviour changes in here https://github.com/sveltejs/sapper-template/commit/b6a92e6337711b827fa1693d27d1d96f2b25c7fd, that's why I'm asking whether you could downgrade your Rollup to `^1.20.0`. Originally, with sapper template you should get files in screenshot 1 (which I haven't confirmed having duplicate contents or not).

**Comment by Ashot-KR** [comment]
@habibrosyad i meant there is no files with content duplicates.
here is result with `sapper@0.28.0` and `rollup@1.32.1`
![image](https://user-images.githubusercontent.com/899218/90021803-68e3aa80-dcba-11ea-8deb-f7c799b76d29.png)
![image](https://user-images.githubusercontent.com/899218/90021925-8a449680-dcba-11ea-85ed-ebaf7e3f1eef.png)
content `main.[hash].css` and `client.[hash].css` contents is identical (except of `sourceMappingURL` of course)

**Comment by Ashot-KR** [comment]
same with `sapper@0.27.16` and `rollup@1.32.1`

**Comment by habibrosyad** [comment]
I could confirm this also happen with `sapper@0.27.16` and `rollup@1.32.1`. I could say that sapper originally behaving that way even before v0.28. You got things in screenshot 2 because you use Rollup 2 with sapper@0.27.16 which I mention as issue in https://github.com/sveltejs/sapper-template/issues/233.

Need to confirm whether this behaviour is intended or not. Maybe @benmccann or @Conduitry knows better in this area.

**Comment by benmccann** [comment]
No, that shouldn't happen. @ajbouh said he's currently working on reimplementing this part, so rather than debug the current version I'll probably wait to see what he comes up with

**Comment by Conduitry** [comment]
Reverting #1306 seems to fix this, but that would presumably break other things.

**Comment by benmccann** [comment]
I think this issue was introduced by https://github.com/sveltejs/sapper/pull/471
