### ISSUE TITLE
The future of Sapper?

### ISSUE THREAD

**Issue by rchrdnsh** [sveltejs/sapper#1421]
Just curious as to the future of svelte and sapper and where I can find out more about it. I heard on a podcast recently that sapper may go away in favor of plugins for svelte, and @Rich-Harris mentioned in a recent Youtube video that eventually sapper may be able to spit out pure html when a component is static, among other cool things...how close is that future? Where can I find out more  about that future? Where is the best place to keep up with the conversation around svelte and sapper in general?

Thanks XD

**Comment by antony** [comment]
Hi @rchrdnsh - the best place is [discord](https://svelte.dev/chat) in the #future channel. Sapper isn't going away in favour of plugins, it may turn into a set of **rollup** plugins, but it'll still exist. Right now we bake the build into Sapper, and it might be better if it was the reverse. How close isn't really predictable - since work is driven by the community, maintainers spare time, and decisions which need a lot of consideration.

**Comment by rchrdnsh** [comment]
Ah, discord is the place. chill, and thank you :-)
