### ISSUE TITLE
Route as modal

### ISSUE THREAD

**Issue by riccardolardi** [sveltejs/sapper#1499]
Question: Is it possible to implement a route so that it opens as a modal / on top of the current page / not replacing the current page, but reflecting in URL, such as asked in https://stackoverflow.com/questions/61185073/route-as-modal-in-sapper

Thanks for any advice.

**Comment by HibiscusJordan** [comment]
Yes it's possible. Simply append a query string to the url like `/users?action=new`. You can then get the `action` from the page store
```javascript
const { page } = stores();
```
and show the modal when `action === new`.

It'd be easier to help you if you would first try to actually implement it and then tell us where you're actual problem is.

**Comment by HibiscusJordan** [comment]
Why don't you simply save the scroll position to `localStorage` then? That would be easier.

**Comment by riccardolardi** [comment]
That's a legit option, too :)

Thanks for the suggestion above using a query string, that's good to know you can do that. I think I can go on from here now. Closing this 👍
