### ISSUE TITLE
Calling Netlify's GoTrue constructor requires an extra .default to be appended.

### ISSUE THREAD

**Issue by dipscom** [sveltejs/sapper#1518]
I am unsure if I should call this a bug or not.

Here is a [bare bones repository with the issue](https://github.com/dipscom/sapper-gotrue-test) I came across.

When using Netlify's GoTrue authentication library, their docs say a simple constructor call is all that is needed to instantiate the library but when trying to do it from inside a Sapper installation, an error is thrown. Adding a `.default` property to the constructor makes the error go away and the library to work as expected.

[Here is the deployed site in Netlify](https://serene-fermat-0987bd.netlify.app/).

**Comment by Conduitry** [comment]
This is going to be caused by a combination of what their library is exporting, how you're importing it, and what your bundler configuration is - and isn't really related to Sapper itself.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
