### ISSUE TITLE
"phantom" modules appearing with recent rollup versions.

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#1564]
**Describe the bug**

Essentially - with the latest version and recent rollup, Sapper generates a zero byte js chunk for a component that is exported with other components from a node module, even if it is not used in the application. It occurs where those other components are used.

If the component *is* used, two chunks with the same name are generated, with different hashes, one of which is 1 byte.

The chunk simply contains a newline.

**Logs**
From the console after `npm run build`:

```
667 B notifier.da518abc.js
           └ node_modules/@beyonk/svelte-notifications/src/notifier.js
       1 B ColourPicker.a049e84d.js
   5.37 kB XIcon.d215763e.js
```

Note the `1 B`yte module which has no contents. The `ColourPicker` module is never imported in the app, so shouldn't generate a chunk.

**To Reproduce**

A small reproduction. The module which makes the issue most obvious is private so I've stuck a copy of it in `node_modules` directly for testing.

Simply inspect the code, see that `ColourPicker` is never imported nor used, and is simply the last `import` in `fields.js` of that module, and then `npm run build` to see an empty (1 byte) js chunk generated for it.

Note that reordering the imports changes this behaviour - the last imported module is always created as an empty file - if it happens to be used in the project, then you get two chunks with the same name and different hashes, one of which is empty.

https://github.com/antony/phantom-modules

**Expected behavior**
A chunk is not generated if the module is not used (tree shaken)

**Information about your Sapper Installation:**

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 658.07 MB / 7.68 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
  npmPackages:
    rollup: ^2.28.2 => 2.28.2 
    sapper: ^0.28.9 => 0.28.9 
    svelte: ^3.28.0 => 3.28.0 

**Severity**
Critical. See Additional Context

**Additional context**
The issue occurs with a rollup version after 2.21.

**Comment by antony** [comment]
A quick update of findings so far:

1. The CSS part of this bug is a misonomer, so removed from the original issue.
2. The ColorPicker.* generated js is empty, but the CSS contains *all* the CSS from the library, even for components that are not used. It contains svelte-[hash] selectors which don't appear anywhere in the actual codebase. It seems like it's generating far too much CSS compared to what is required.

**Comment by antony** [comment]
I've figured out what happens, and recreated it. I'm now building a simplified version for debugging.

1. You have a project which has a module which exports 3 components from an `index.js` file
1. The first two (A, B) are used in the project, the third (C) is not.
1. A is used in route R1
1. B is used in route R2
1. { A, B } is used in route R3 
1. A is used in component E1

The result:

1. The module is built and named "C.[hash].js" because it is named after the last imported dependency in `index.js`
1. The components inside it are all used elsewhere in different combinations, so they are all initially added to the chunk C.[hash].js but then later pulled out and build as A.[hash].js and B.[hash].js because they are consumed individually.
1. This leaves the strangely named "C.[hash].js" as a single byte javascript module and dependency of everywhere which uses any  of A, B, and C.
1. This also leaves C.[hash].css containing *all* the css for each of A, B, and C, prefixed with the `svelte-[css-hash]` prefixes, even though C was never used at all, and the css-hash for A and B don't match any of the Svelte dom output.

So I think the issues we have are:

1. The css tree shaking is happening before the chunks are calculated, leaving orphaned and surplus CSS
1. The module tree shaking isn't disposing of modules which would end up empty.

I'll build out the simplified repro so that you can see the net result more easily, but for now you can still make this occur with the attached project.

**Comment by benmccann** [comment]
> The css tree shaking is happening before the chunks are calculated, leaving orphaned and surplus CSS

There's no such thing as "css tree shaking", but rather Rollup just has JS tree shaking. Rollup itself doesn't know anything about CSS.

`rollup-plugin-svelte` will output files like `mycomponent.css` and `mycomponent.js` which imports the former. That's done just to pair the content together, but it's kind of a trick. Rollup treats `mycomponent.css` as a JS file. If you do nothing then Rollup will encounter the CSS, try to treat it as a JS file, and then crash. `rollup-plugin-css-chunks` takes the CSS and [deletes it](https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L90) so that Rollup can continue as normal without worry. `rollup-plugin-css-chunks` will then find which CSS corresponds to JS files that were placed in the same chunk, [concatenate them together](https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L142), and then [output it as a CSS file](https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L168).

One thing I just noticed while writing this explanation that's a little funny looking to me is that `rollup-plugin-css-chunks` is [calculating a hash for the filename](https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L147). We previously had the CSS chunking functionality within Sapper before outsourcing it to `rollup-plugin-css-chunks`, but [did not have a hash in the name](https://github.com/sveltejs/sapper/blob/86932d6bd8b5351f0d94ff34aeb9e1a1cb404f3b/src/core/create_compilers/RollupCompiler.ts#L110) and Rollup would add it automatically. I wouldn't necessarily expect this to cause your issue, but wonder if it might be something we could simplify in `rollup-plugin-css-chunks`.

**Comment by antony** [comment]
I've updated [the repro](https://github.com/antony/phantom-modules) to be the smallest possible Sapper app I can create. The fields module now exists inside the app and is now just 3 divs. The problem still exists.

Hopefully this will make it easier to determine exactly how the 1 byte module is being created and why.

**Comment by antony** [comment]
@benmccann based on your comments in chat, and what you've said here, indeed fixing this line:

```
return {code: '', moduleSideEffects: 'no-treeshake'};
```

to be

```
return {code: '', moduleSideEffects: false};
```

eliminates the unused css, and and removes the orphaned module.

So I guess the question is, why it has `no-treeshake`. It means including a load of dead CSS, and, obviously, causes the phantom module issue.

**Comment by domingues** [comment]
> One thing I just noticed while writing this explanation that's a little funny looking to me is that `rollup-plugin-css-chunks` is [calculating a hash for the filename](https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L147). We previously had the CSS chunking functionality within Sapper before outsourcing it to `rollup-plugin-css-chunks`, but [did not have a hash in the name](https://github.com/sveltejs/sapper/blob/86932d6bd8b5351f0d94ff34aeb9e1a1cb404f3b/src/core/create_compilers/RollupCompiler.ts#L110) and Rollup would add it automatically. I wouldn't necessarily expect this to cause your issue, but wonder if it might be something we could simplify in `rollup-plugin-css-chunks`.

I don't remember why I did that. :D Probably to produce the .map file name: https://github.com/domingues/rollup-plugin-css-chunks/blob/c90514fecd8624953baa5001b35c8f2d8ad86f5b/index.ts#L161

**Comment by benmccann** [comment]
>  Probably to produce the .map file name

Ohh, yeah, I bet that's it. We never had a `.map` file. Only inline source maps, so that's probably why.

**Comment by domingues** [comment]
A new version of the plugin has been published that should fix this issue, it also supports the last version (7) of the svelte rollup plugin.
