### ISSUE TITLE
Enable disabling sourcemaps in development mode:

### ISSUE THREAD

**Issue by samccone** [sveltejs/sapper#1687]
Currently this value is determined from the env being dev or not, I would like to be able to turn this off in development mode due to it costing a non-trivial amount of time during the save to reload experience.
https://github.com/sveltejs/sapper/blob/3c01d9300839358e01387c388527f3ec14b0e35b/src/config/rollup.ts#L4

Preferably this would be easily overridable via an env var or alternative.

**Comment by benmccann** [comment]
The issue here would be that Sapper has no way of handling configuration (https://github.com/sveltejs/sapper/issues/1216). That's been a bit of an issue that's blocked a number of enhancements. Luckily that's been addressed in SvelteKit. But I don't think we'd want to introduce configuration handling into Sapper this late in the game, so your best bet is probably just to wait for SvelteKit which is substantially faster

**Comment by samccone** [comment]
ack, happy to close this out then. Thanks much.
