### ISSUE TITLE
onstate not called instead of .observe after Svelte v2 upgrade

### ISSUE THREAD

**Issue by johanalkstal** [sveltejs/sapper#247]
I've upgraded Svelte in my Sapper app and everything seems to be working fine except for one thing.

```
// From component A
this.state.set({
  notification: 'Some notification'
})

// In component B
onstate({ changed, current }) {
  if (changed.notification) { // Code never enters here after creation.
    // Blah...
  }
}
```

`onstate` is called when the component is created, with `changed` and `current` being `undefined`, but calling `this.state.set` from somewhere doesn't trigger it again.

Might I have missed something in the upgrade that relates to Sapper?

**Comment by Rich-Harris** [comment]
Your component B code is only listening for changes in component B's state — if you want to listen to store state you would need to add a store listener:

```js
export default {
  oncreate() {
    const listener = this.store.onstate({ changed, current }) => {
      // ...
    });

    this.on('destroy', listener.cancel);
  }
};
```

(You *can* cheat and check for `changed.$notification` — note the `$` — in `onstate`, but it'll only be present if the component is specifically observing that property because it appears in the markup or in a computed property.)

**Comment by Rich-Harris** [comment]
@johanalkstal is this issue resolved or do we need to keep it open? thanks
