### ISSUE TITLE
Project tagline

### ISSUE THREAD

**Issue by molily** [sveltejs/sapper#263]
Hi there,

I’ve stumbled on this interesting project several times. As a total stranger to this project I’d like to comment on the tagline that puts me off: “Military-grade progressive web apps, powered by Svelte”. I don’t think it’s clever or appropriate to use “military-grade” prominently in a JavaScript project description.

I understand it’s a tongue-in-cheek metaphor for robust, high-quality, well-tested, fault-tolerant etc. and goes well with the project name, a type of soldier. Robust JavaScript is something I advocate for as well. I’m happy to find a project advertising robustness as a main goal. Still, “military-grade” is martial language that is typically used to describe weapons, explosives and related technical equipment that is used to kill people efficiently.

Unsurprisingly, JavaScript is used by the military-industrial complex as well. Large companies from this sector are releasing and sponsoring open-source JavaScript projects. This fact is often neglected or dismissed by the JavaScript community. “Military-grade” JavaScript is a sad reality instead of innocuous irony. That’s why such a project description (and to a lesser extent, the project name) leaves a bad aftertaste even if the project in itself has nothing to do with the military and surveillance industry.

Please consider changing the tagline.

**Comment by zachleat** [comment]
Hey y’all—I encouraged @molily to file this issue. I think it’s worthy of discussion! Thanks!

**Comment by Rich-Harris** [comment]
Thanks for starting this discussion.

First, let me put my cards on the table: I don't view the military as 'bad', or something to distance oneself from. War is bad, and the politics involved in military decisions is often bad, but military forces (at least in democratic societies) are not indiscriminate killing machines; a soldier is as likely to be involved in peacekeeping and humanitarian missions as in warfighting. I was briefly involved with the military many years ago, and I found my colleagues to be thoughtful, dutiful, politically aware people who viewed violence as a last resort.

Secondly, as a marketing term, 'military-grade' is usually the sort of thing you find associated with things like phone cases, hiking boots, camping gear and so on. I don't personally consider it to be a phrase associated with violence, and I'd be surprised if it was commonly understood that way.

Nothing is set in stone; I like the tagline, but if there's a consensus in favour of changing it then we can. I will say, though, that finding memorable and descriptive phrases for software projects is incredibly hard, and it would be a shame to end up with a bland adjective salad.

I would be interested to hear opinions from others in the community. Thanks!

**Comment by silentworks** [comment]
I've seen many open source projects use the term **military grade encryption**, I am sure it doesn't mean war grade encryption nor kill grade encryption. I don't see an issue with the tagline, its different and standout to what everyone else is using. I too agree with @Rich-Harris about the military not being a bunch of people who are just war hungry killing machines. I am not against changing the strapline, but I think for the reasons listed above seem a bit over the top.

**Comment by tomcon** [comment]
Ordinarily the tag line is fine but I'd agree that it doesn't feel quite right here for whatever reason.

Sapper - High Performance Universal Svelte Applications   

?

**Comment by arxpoetica** [comment]
It may be impossible to measure who may or may not find the term "military-grade" offensive. The numbers of people who take deep offense may be (for example) small but highly vocal.

My vote would be to keep it, since I find the modern vogue of pleasing everyone a downright shame.

Yet a conciliatory tone may take the project further, no matter what is right or wrong. So my actual vote: try and find some other language or at least try and walk the line.

But. My final, final vote: don't waste too much time on marketing. Just keep building awesome products because Sapper and Svelte are among the best open source projects ever, and I speak with little hyperbole.

**Comment by cphoover** [comment]
Avoiding the long drawn out debate regarding the military industrial complex, or the ethics of global war, I just think it comes off as hyperbolic and meaningless.

Also many people who have worked in defense/intelligence will likely tell you that military grade technology often lags behind what is available in the private sector. When I think military I don't think nimble/agile technology, I think slow moving, massively wasteful, and over-engineered.

**Comment by kudos** [comment]
I don't actually find it "offensive", I just find it weird and unnecessary in this context.

**Comment by millerhooks** [comment]
@silentworks The first thing I thought of was people using the term **Military Grade Encryption**. I built a startup that did delivery of legal depositions. Though we weren't necssisarily under HIPPA guidelines, potentially we could cross into that territory so our CEO really wanted to use that phrase. That or **Bank Grade Encryption**. I had seen both used many times. They were meaningless to me, but I thought maybe they have some industry usage I don't know about. Before we went to put that on our marketing materials, I went and did some digging. Both phrases are meaningless. In fact at least here in the US but I assume abroad as well, understaffed military IT services rely on infrastructure that is often out of date.

At best, the term is annoying hyperbole but in my opinion it distracts from important aspects of crypto and can even harm the debate of civilian used crypto. Law enforcement and governments everywhere hate crypto and would love to pass laws against strong encryption. Language like this makes people think that there is some sort of secret sauce that only the government can have and normal people do not. Some places do have laws about strong encryption, but fun fact, you can't stop a person from doing math.

The tag line for this app reminds me of that problem. I won't touch the issues that some people might have contributing or using a product that might be funded by or used for war. Those people do exist, and in my industry I'd say there are a lot of them. But especially because the only excuse for the "cool" tagline is that is kind of cute? I suggest y'all should change it because you have an opportunity to say something actually descriptive and not something cute that alienates people. Weather it's because they don't like the military or just because they think it's dumb.

Cute things don't age well with software project either. I'm reminded of Homer Simpson when he was in his singing group the Be Sharps. It was the perfect name "that’s witty at first but that seems less funny each time you hear it.".

Don't be that guy, be sharp! Spend a minute and come up with a tag line that says something about how your software works and why we should care.

**Comment by SCdF** [comment]
This is another vote to change the tagline to something else.

I don't think I could pitch this tech to my company with that tag line around. It's just to "exxxxtreeeeeme" to be taken seriously: it reminds me of this tweet: https://mobile.twitter.com/whitequark/status/986217575569735680

> Secondly, as a marketing term, 'military-grade' is usually the sort of thing you find associated with things like phone cases, hiking boots, camping gear and so on. 

Totally! I have a backpack that is "military grade" (cordura 1000 and all that), so I get the marketing there. However, as a choice for a JS framework I don't think the metaphor works. It is Javascript after all.

**Comment by andreujuanc** [comment]
I think it's fine the way it is now. Back when I first read it, i just thought:
>  hope this thing npm-starts on first try. -Me

And it did. 🍺

**Comment by LorbusChris** [comment]
+1 for changing it. To me personally it is somewhat offputting. Not caring too much about it tho.

**Comment by Rich-Harris** [comment]
Thanks everyone for weighing in on this issue. It became painfully apparent in the [Hacker News thread](https://hn.svelte.technology/item/17473181) about Sapper that a) most people don't know what a sapper is and b) 'military-grade' creates a bad first impression for people who have seen it derided in other contexts.

So I'm proposing changing it to something simpler — 'Rugged web apps'. Any thoughts before I go ahead and deploy this? https://sappersveltetechnology-nnljacvnrn.now.sh/

**Comment by rob-balfre** [comment]
'Rugged' could mean different things to different people. Maybe just something more straight forward — 'The official framework for creating PWAs with Svelte'.  

On a related note, a rebrand of the logo would probably help too (for both Sapper and Svelte).  I love the rollup one, who did that?

**Comment by Rich-Harris** [comment]
@tomcon had a suggestion I really like — [rock solid](https://sappersveltetechnology-rxtbibljxp.now.sh). Doesn't have the same negative bulky connotation of 'rugged', and sort of means the same as 'indestructible' without inviting 'lol indestructible whatevs' from the peanut gallery.

@rob-balfre yeah, I considered that — the thing that gave me pause was that not many people know what Svelte is, so most people wouldn't really have any idea whether that was a good thing or not. I agree about the logo — @simonlayfield and I were chatting the other day about a visual refresh.

(As for the Rollup logo, people ask me that all the time! It was @jlmakes — Julian, I hope you got a commission or two out of it 😀)

**Comment by simonlayfield** [comment]
I'm keen to be involved in whatever needs attention design-wise.

'Sapper' is a little tricky as far as a visual connection, especially if the actual definition of the word is to be avoided 😬 . 'Rollup', for instance, has a literal meaning that can tie in nicely (great logo 👍).

If I'm honest I'm not sure the logo/typeface would need too much work anyway. I think if the Sapper homepage were to be given a bit of attention, and perhaps the inclusion of some more engaging content then that could be enough to enhance the brand all round.

That being said, I'm always keen to throw ideas together if there's the demand for it. If anyone has any thoughts around it they want to share, then go ahead. Always good to keep the ideas flowing.

**Comment by simonlayfield** [comment]
Alrighty, I've started throwing a couple of ideas together. Should the broader discussion of svelte/sapper design continue here or is it better of as a separate issue?

**Comment by Rich-Harris** [comment]
@simonlayfield awesome! Can't wait to see 🙌 Let's start a new thread — perhaps on https://github.com/sveltejs/svelte.technology ?

On the tagline question, this came up in Discord yesterday (thanks @jacwright!):

> Sapper — the next small thing in web development

I think that's a really fun idea. Alternatively, that could be used for Svelte itself:

> Svelte — the next small thing in web development
> Sapper — rock solid web apps, powered by Svelte

**Comment by simonlayfield** [comment]
Oh, well, I wouldn't get excited just yet. I've kept things pretty close to the way they are. Anyway I'll get a thread going over on the Svelte repo and we can go from there.

FWIW I'm cool with both of these:

> Svelte — the next small thing in web development
> Sapper — rock solid web apps, powered by Svelte

...but I would kind of miss 'The magical disappearing UI framework' because it better describes the problem Svelte solves (IMO) and also may have a longer shelf life than 'The next small thing'. I do like it though.

Anyhoo. Much of a muchness. All good options!

**Comment by fusionstrings** [comment]
I see "military grade" as a quick and robust turnaround. Say how military builds bridges or carry out rescue operations. That means a reliable set of conventions can be followed to get a desirable result.

I feel Sapper is all about that. It asks you to follow certain conventions to build something very quickly and which is robust but at the same time disposable.

At this point, this seems like a perfect example of bikeshedding. For God shake how many non real military references one wants to see of "bulletproof", "battle tested". What was "Browser wars" about?

Otherhand as I get the feeling it's bound to change, I propose following.

### **Sapper** 
**All weather apps. Boot quickly build rapidly**

**Comment by simonlayfield** [comment]
@fusionstrings that suggested strap line. That's strong 👏

**Comment by fusionstrings** [comment]
@simonlayfield Thanks. I just hope real goal and efforts don't get lost in nuance. I just don't like always being politically correct. 

For me it's more important creators should be able to call it whatever they want. It brings sense of belongingnesss. I don't see coding much different than poetry. Yet can we ask to change the words in a poem?

**Comment by simonlayfield** [comment]
We'll be giving Sapper a bit of a branding/visual refresh in coming weeks. We're just about to work through some Svelte stuff, and then will move on to Sapper.

It's great to have people contributing ideas so keep an eye out for developments there and feel free to chime in (that goes for everyone reading this).

In the meantime Svelte stuffs are happening over here:
https://github.com/sveltejs/svelte.technology/issues/335

**Comment by arggh** [comment]
My two cents about the "military grade" tag line. I like it. It caught my attention and differentiated Sapper from the others before I even knew what it was.

Where I live, nobody would get upset over that. Combining that "claim" with something like a Javascript library is surprising, clever and gets people interested.

If I try really hard, I can understand why one half of people in the US might get upset. Or somewhere else where war in general is a bit controversial subject.

That said, I do like the "The next small thing..." idea, but "rock solid web apps" sounds quite dull. "Military grade" is way better than "Rock solid".

**Comment by elhigu** [comment]
> In war, the soldiers who build bridges, repair roads, clear minefields and conduct demolitions — all under combat conditions — are known as sappers.

> For web developers, the stakes are generally lower than for combat engineers. But we face our own hostile environment: underpowered devices, poor network connections, and the complexity inherent in front-end engineering. Sapper, which is short for Svelte app maker, is your courageous and dutiful ally.

Actually for me that part of docs was more off putting than the tagline, which made me look for this issue. 

Personally I really don't care about it. People writing open source project should be allowed to express their own taste what is cool in their opinion freely and this is pretty harmless anyways.  

I'm still sad about the fact that Testacular had to change its name to Mocha, because of this kind of issues and the same happened when Moron.js (ORM) was renamed to Objection.js.

**Comment by antony** [comment]
In my experience people immediately balk at 'Military Grade' because they don't understand the Sapper reference. They find it arrogant and it's off-putting for them, they want to know what makes it `military grade` and want proof. It is an immediate negative against the project for them. This has happened on numerous occasions.

I'm not offended by the military connection, though I can understand that, but I certainly think it does more harm than good.
