### ISSUE TITLE
target="_self" on <a> causes full page load

### ISSUE THREAD

**Issue by UnwrittenFun** [sveltejs/sapper#265]
With the following
```html
<a href="/" target="_self">Link</a>
```

it does a full page load of '/'

_self is the default so I would expect having it set not to make any difference

**Comment by Conduitry** [comment]
I believe this is intentional (though perhaps it ought to be documented). When a routing system works by intercepting clicks on links, using `target='_self'` on a link is a semi-standard way to let the routing system know that this link _should_ force a page load, even if its href looks like it could be part of the same app.

**Comment by UnwrittenFun** [comment]
Should definitely be documented if intended 👍 

I ran into this as an issue where I had a Button component which could be an `a` or `button` tag depending on if `href` was specified, I passed through `target` to the element with a default to `_self` as otherwise it would set it to undefined which always opens in a new tab.

**Comment by EmilTholin** [comment]
Yes, [it's intentional](https://github.com/sveltejs/sapper/blob/25f0d9459591cfa31c536172f48df7f2f2cd804b/src/runtime/index.ts#L192-L193). An addition to the documentation would be awesome.

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/sveltejs/sapper.svelte.technology/issues/31
