### ISSUE TITLE
Serve txt file at assets folder

### ISSUE THREAD

**Issue by lzl** [sveltejs/sapper#316]
sapper 0.14.2

I put a `demo.txt` file into assets folder, then visit `/demo.txt`.

I expect to see the content of `demo.txt` file.

It shows me 404 route instead.

**Comment by Rich-Harris** [comment]
This is extremely weird — I was able to reproduce it briefly, but now when I create a fresh project and add an `assets/demo.txt` file it works correctly.

Can you try devtools -> application -> clear site data to rule out service worker/cache nonsense?

**Comment by lukeed** [comment]
Yeah, using `sirv` in development will do this. It traverses its target folder's contents at startup & that's it -- unlike `serve-static`, which does a fresh traversal of the file structure (no cache) _every_ request. This is the sole reason why `sirv` is much faster... and aimed at production.

> Explained at the top of [`sirv`'s readme](https://github.com/lukeed/sirv/tree/master/packages/sirv#sirv-), second paragraph~ 

Ideally, for dev, the `app/server.js` would be restarted programmatically, or (in dev env only) Sapper can perform a last second check on `/client|assets/*` requests before rendering 404 on those routes. Otherwise restarting the server will always show the new `assets`.

**Comment by lukeed** [comment]
Updated `sirv(-cli)` to verion `0.2.0` which now includes a `dev` mode. When enabled, it skips the file cache entirely so that you can add/remove files without needing to reboot.

As indicated by the name, still not meant for production use. You can do something like this:

```js
import sirv from 'sirv';
import polka from 'polka';
import sapper from 'sapper';
import compression from 'compression';
import { manifest } from './manifest/server.js';

const { PORT, NODE_ENV } = process.env;
const isDev = NODE_ENV === 'development';

polka() // You can also use Express
	.use(
		compression({ threshold: 0 }),
		sirv('assets', {dev:isDev }), //<~ here
		sapper({ manifest })
	)
	.listen(PORT)
	.catch(err => {
		console.log('error', err);
	})
```
