### ISSUE TITLE
Service worker requests unused resources

### ISSUE THREAD

**Issue by fusionstrings** [sveltejs/sapper#346]
Service worker still requests resources even if not used in content.

## Steps to reproduce
- Bootstrap a new project using `degit sveltejs/sapper-template <app-name>`
- Open `routes/index.html`in an code editor
- Remove reference of Borat image, which is this line https://github.com/sveltejs/sapper-template/blob/master/routes/index.html#L8
- `npm run build && npm start`
- Open `http://localhost:3000`in browser with network tab open
- Notice "great-success.png" still being requested from service worker

## Repository for reproducible code
- https://github.com/fusionstrings/sapper-sw-issue

## Deployed URL to now
https://sapper-sw-issue-cxjdzagtis.now.sh

**Comment by Rich-Harris** [comment]
This is expected behaviour — the default service worker imports `assets`, which is an array of files in the assets directory, the expectation being that if it's there, you'll probably need it at some point:

https://github.com/sveltejs/sapper-template/blob/611237e39303f0e42ce42d53ff6eb2af4b6cbec1/app/service-worker.js#L1-L19

If you don't need offline support, you can remove asset caching from the service worker, or filter the list to just cache the things you definitely want. 

Reasonable people could disagree on what the correct defaults should be, though that discussion should take place on the sapper-template repo so I'll close this.

**Comment by fusionstrings** [comment]
I understood why this happens. My reasoning behind the issue was that users of Sapper would expect assets to be loaded on demand similar to how it loads css and js. 

Certainly, different people have a different opinion about what is correct behaviour but by convention, I feel that Sapper should handle assets similar to other resources.

I will open an issue in sapper-template assuming service worker implementation is out of concern from Sapper.
