### ISSUE TITLE
Export Hangs Forever on Links with spaces

### ISSUE THREAD

**Issue by N-McA** [sveltejs/sapper#355]
If you have a space at the end of an href; `sapper export` hangs forever.

A fairly minimal example is provided on the latest release (0.15.7) in this repo based on the example project: 

https://github.com/N-McA/export-bug-example

**Comment by N-McA** [comment]
So, from my very brief look at the code, this particular issue is easy to fix. However, we should probably take steps to prevent similar issues from occurring in future. An aggressive timeout on the fetches might help?

**Comment by Rich-Harris** [comment]
Thanks for the repro — it looks like this works in more recent versions, most likely because we switched from using Cheerio to extracting links ourselves.

We also added an export timeout (defaults to 5 seconds, configurable with `--timeout`) recently which should indeed prevent similar issues happening in future, so I'll close this.
