### ISSUE TITLE
`sapper export` doesn't find server routes in `app/client.js`

### ISSUE THREAD

**Issue by mhkeller** [sveltejs/sapper#438]
Taking the svelte.technology repo as an example, the server route `fetch('api/guide/contents')` is called here in `app/client.js`: https://github.com/sveltejs/svelte.technology/blob/71e483acd30eab0d8db0b42d2a5faefd3013b2b4/app/client.js#L11-L13

But if you do `npx sapper export`, you won't get a corresponding baked file at `export/api/guide/contents` and so you can't serve sites with this configuration as static sites. I imagine this is because `sapper export` doesn't look for route calls in every file and maybe only looks inside of `preload` blocks? fwiw I'm not sure if sapper should support crawling all the files like this but who knows?

**Comment by Rich-Harris** [comment]
When you run `sapper export`, client.js never runs — all it's doing is firing up the server and visiting localhost:3000 (or whatever) and recursively fetching blobs of HTML. There's some special handling for server routes that are requested inside `preload`, but that's it.

If you visit https://svelte.technology/guide and https://sapper.svelte.technology/guide with JS disabled, you'll see that only Sapper has the left rail with the guide contents. That's because Sapper does [this](https://github.com/sveltejs/sapper.svelte.technology/blob/master/app/server.js#L23-L25), and I haven't got round to applying the same thing to the main site. I'd probably recommend that approach.

**Comment by d4h0** [comment]
@Rich-Harris: Your last link dosn't work anymore. Did you (or someone else) document this approach somewhere else, or can you update the link?

**Comment by ghyath5** [comment]
@mhkeller 
How did you fix this issue ?

**Comment by mhkeller** [comment]
@ghyath5 sorry I don't remember!
