### ISSUE TITLE
"Failed to fetch dynamically imported module" when NODE_ENV=production

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#464]
I have a deployment that results with the error:

`Failed to fetch dynamically imported module: https://esg.censible.co/client/index.ba12ed5c.js`

The file in question is downloaded however some of the following chunks result with a 404.

![screenshot from 2018-10-03 22-43-36](https://user-images.githubusercontent.com/3664/46450194-09cbbb00-c75e-11e8-8ce5-ecf8b09ef00b.png)

Setting NODE_ENV=staging fixes the error.

**Comment by nsivertsen** [comment]
I'm getting a similar error. The production site runs fine in most browsers, but when testing older versions of iOS Safari in the Xcode simulator (e.g. iOS 9.3 on iPhone 6), I'm seeing a brief flash of the pre-hydrated site before getting a "500 undefined" error. There seems to be no relevant error logged to the console, only some CSS chunks that are not found for some reason:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (index.dd5d4b26.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (chunk.9e60d83d.css, line 0)
```

When switching to dev mode, the site loads fine, but doesn't run as an SPA (clicking on links results in the new page being fetched from the server), although this could be due to something else. I'm getting the following logged to the console:

```
SyntaxError: Unexpected use of reserved word 'import'
```

**Comment by nsivertsen** [comment]
I just double-checked, and for me, it's not `NODE_ENV` that makes the difference, but whether I'm running the app with `sapper dev` or `node __sapper__/build`.

**Comment by Rich-Harris** [comment]
@btakita is there any kind of authentication layer involved? I ask because I hit a situation recently where I couldn't load modules because my app was behind [identity-aware proxy](https://cloud.google.com/iap/). Long shot I know...

@nsivertsen The `Unexpected use of reserved word 'import'` message is probably a `console.error` that I erroneously left in (part of the feature detection) and should be gone in 0.22.10. If not it might indicate a bug in the module transformation. The CSS thing is weird. Is it related to whether or not a `--legacy` build is running?

**Comment by btakita** [comment]
@Rich-Harris There's no authentication layer to load the app.

**Comment by nsivertsen** [comment]
@Rich-Harris the `Unexpected use of reserved word 'import'` message is gone in 0.22.10. The CSS thing and the 500 server error go away when not doing a `--legacy` build. The site then runs in non-SPA mode in the affected browsers (for example iOS 9.3 Safari), so lazy loaded images and so on are all broken, but at least the content is readable. Any idea as to what might be going on?

**Comment by btakita** [comment]
One difference that I can think of is the app uses a DNS & CDN (Cloudflare). Perhaps there's some issue with the CDN proxy?

**Comment by nsivertsen** [comment]
I've been seeing a lot of

```
Failed to fetch dynamically imported module
```

errors lately, and I think I've found the cause:

Sapper sets `Cache-control: max-age=600` headers when `NODE_ENV=production`:

https://github.com/sveltejs/sapper/blob/4d7d44859742cf5b7b9147c2afa829cb4ad242b5/templates/src/server/middleware/get_page_handler.ts#L45

When an update is pushed to the server, some CDN and client caches still have the old HTML, which refers to hashed assets that no longer exist, causing the error.

@btakita is that consistent with what you're seeing?

So it seems this issue is related to #389, and I guess #415.

I think it would probably be good to have the option of overriding the cache headers.

**Comment by mrkishi** [comment]
I've actually been thinking about that. Instead of `rm`ing the whole build directory on build, wouldn't it be nice to have sapper only delete files older than X time?

We could have both `sapper build` and `sapper rebuild`, where build has the optional `--keep` defaulting to 1 week and rebuild would be an alias to `sapper build --keep 0`.

**Comment by nsivertsen** [comment]
@mrkishi sadly, that wouldn't work in environments like Now.sh that start from scratch for every deploy.

**Comment by btakita** [comment]
@nsivertsen Yes! That is consistent with what I'm seeing. I had to add a cache-buster to fix the problem.

**Comment by nsivertsen** [comment]
What confuses me is that I'm seeing these errors long past the `max-age`. In some cases clearing the cache is the only way to fix them.

**Comment by nsivertsen** [comment]
This seems to be related to a Rollup bug where hashes of files are not invalidated for files that depend on files that have changed (https://github.com/rollup/rollup/issues/2435).

This would explain why I'm seeing the errors long past the `max-age` of the HTML entry points. The JS assets are cached as immutable assets, and the JS entry point doesn't change.

**Comment by nsivertsen** [comment]
@btakita as far as I can tell, we're not seeing any issues anymore. The Rollup patch seems to have fixed it for us. The error you've pasted seems like a different error than before, no? Are you back on Rollup?
