### ISSUE TITLE
service worker: static files hashes

### ISSUE THREAD

**Issue by laurentpayot** [sveltejs/sapper#527]
Currently we can get `files` (an array of everything in the `static` directory) by doing so:
```js
import { timestamp, files, shell, routes } from '../__sapper__/service-worker.js';
```
Then the template service worker puts these static files directly in a timestamp-named cache.
But to avoid reloading all my static files (especially my CSS framework in global.css) when a js file is updated, hashes of the static files are needed to detect when they are _really_ modified.

Is it possible to modify `files` or to add an `hashes` named export to get an **object** like below?
```js
export const hashes = {
	"global.css": "d739dfc3",
	"img/my-logo-192.png": "76dd89df",
	"img/my-logo-32.png": "39ad9914",
	"img/my-logo-512.png": "7a435e16",
	"img/my-logo.svg": "17225699",
	"manifest.json": "5cdfe09c"
};
```
It would really save unneeded reloads, meaning energy, and of course make the world a better place :wink:

**Comment by benmccann** [comment]
Rather than making a separate map, can we just put the hashes in the filenames? That will allow the files to be cached by CDNs.

[I raised an issue in the template](https://github.com/sveltejs/sapper-template/issues/229) to add hashes to the filenames and provided the code to do so there. If I don't hear any objections I'll send it as a PR.

**Comment by benmccann** [comment]
Closing this since https://github.com/sveltejs/sapper-template/pull/248 was merged
