### ISSUE TITLE
Rollup config: Extracted CSS sourcemaps always generated

### ISSUE THREAD

**Issue by laurentpayot** [sveltejs/sapper#537]
`config.client.output()` always return an object with a truthy `sourcemap` property, so I get sourcemap files for both js and css files.

Even when using 
```js
output: {...config.client.output(), sourcemap: dev}
```
when `dev` is falsy I still get sourcemap files for css files (but not for js files).

Is it related to #421 ?

**Comment by Teoxoy** [comment]
This happens because rollup doesn't care about other sourcemaps than `js` ones.

The only way to get this to work is to pass in a `sourcemap` option to [`rollup-plugin-svelte`](https://github.com/rollup/rollup-plugin-svelte). This not currently supported but I am looking into it and will probably start a PR for it.

**Comment by Teoxoy** [comment]
Looks like sapper does some custom plugin injection for rollup and the answer was to implement this into sapper. I included a commit that will add this functionality in my PR.
