### ISSUE TITLE
Function called outside component initialization

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#592]
I'm getting a `Function called outside component initialization ` error from a sapper v0.26.0-alpha.10 project.

A component is being loaded from a index.html route component. This component is calling onMount, beforeUpdate, afterUpdate, or onDestroy.

I tried moving onMount into a setTimeout & the same issue occurs.

Unfortunately, I'm not able to reproduce it in the repl. Hopefully, this will be fixed or a reproduction for this issue will emerge.

**Comment by btakita** [comment]
The generated code calls `.$$render` instead of `.render` on the component.

**Comment by btakita** [comment]
This is a svelte issue. https://github.com/sveltejs/sapper/issues/592

**Comment by btakita** [comment]
It looks like the issue stems from having "svelte" as a dependency instead of a dev_dependency in `package.json` within the sapper project.

This causes `import 'svelte'` to load the rollup excluded npm package's `set_current_component` instead of from within the sapper generated `server.js`.

**Comment by mdskinner** [comment]
The above wasn't relevant for me - from the docs:
`A <script> block contains JavaScript that runs when a component instance is created.`

`A <script> tag with a context="module" attribute runs once when the module first evaluates, rather than for each component instance.`

You can't call a function outside of component initialization...  You can't call a function within `<script context="module">`

Moving it to the standard `<script>` tag works fine

**Comment by hugosenari** [comment]
I know that since we bundle it, makes no difference if svelte is dep or devDep, but makes sense to me set things that my code import as dep and even eslint complains about it.

DX:
- start sapper project; :smile: 
- configure eslint; :smiley: 
- eslint say that svelt should be dep; :thinking: 
- update package.json; :man_shrugging: 
- build fails with crypt error; :cry: 
- try to figure what the hell; :confused: 
- google it; :crossed_fingers: 
- come here (if you have luck); :four_leaf_clover: 
- revert package.json; :disappointed: 
- add ignore error to eslint; :disappointed: 

Maybe we should offer better solution for this.

**Comment by Conduitry** [comment]
What eslint rules says that `svelte` should be a prod dependency and not a dev dependency? That seems to be where the real problem is.

Having the bundler config bundle dev deps and leave prod deps as external seems to be the sanest thing it could default to, and I don't see us wanting to change that.

**Comment by hugosenari** [comment]
Thank you for replying fast.  :peace_symbol: 

[ESlint rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) about dependencies.

We could at least try to offer better error message for this, before it becomes our next [NullPointerException](https://softwareproduction.eu/wp-content/uploads/2017/06/1qxh2q-1.jpg), [Segmentation Fault](http://guilload.com/assets/media/pyisaac/segfault.jpg) or [Kernel Panic](https://o.aolcdn.com/images/dims?thumbnail=640%2C&quality=80&image_uri=http%3A%2F%2Fwww.blogcdn.com%2Fwww.tuaw.com%2Fmedia%2F2008%2F05%2Ftrent.jpg&client=amp-blogside-v2&signature=d2a4686238c77194dbed032c88b1ac840c05e60a) ([more](http://screeneggs.com/wp-content/uploads/2019/03/epkjc5r6ltj21.png) [memes](https://instagram.fcgh7-1.fna.fbcdn.net/v/t51.2885-15/e35/59679526_500781763794820_4749243527144228792_n.jpg?_nc_ht=instagram.fcgh7-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=pM1QUJx9V1QAX-Nt-Yv&oh=a7d2c7ff40930e191dcf7799d873ce74&oe=5E9E56B4)). 

When the message say `function was called outside component initialization` first will look at my code and last at my configuration.

In the last case we could suggest [dependency-cruiser](/sverweij/dependency-cruiser) or similar in templates.

**Comment by Conduitry** [comment]
According to the readme for that plugin, it should allow imports of devDependencies unless you specifically configure that to be disallowed, so I'm not sure what you're seeing there. And the Sapper template can't really guard against it if you decide to move something from devDependencies to dependencies. I don't think we need more tooling here.

**Comment by ANovokmet** [comment]
Got this issue migrating my project to Svelte 3.
The problem was in my rollup.config.js.
`plugins: [svelte(), commonjs(), nodeResolve(), typescript()]` 
did not result in a working bundle. When fixed to 
`plugins: [svelte(), nodeResolve(), commonjs(), typescript()]` 
the error disappeared.

**Comment by jagrut-18** [comment]
This `Function called outside component initialization` error occurred in my case because I called `createEventDispatcher()` inside a function.
**Error in this case:**
![image](https://user-images.githubusercontent.com/49028352/107374324-79f86180-6b0d-11eb-910a-c91bdc05b690.png)

**Fix in my case:**
![image](https://user-images.githubusercontent.com/49028352/107374262-6816be80-6b0d-11eb-881b-57c79f09abbf.png)

**Comment by webdev23** [comment]
Instead of the common form 

`  export async function myFunc(){  }`

this works similarly like this:

`  export const myFunc = async () => {  }`
