### ISSUE TITLE
(Rollup v3) `preload` not getting called consistently on server, but always runs on client

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#594]
**Update** it's consistent, and it has to do w/ style preprocessing.

Unfortunately, I've had a very difficult time pinning this down, but it appears that preload sometimes doesn't get called *on the server*. It's totally inconsistent, and I can't reproduce it on anything reliable, but it seems to be happening when I switch to different pages with different preloads (and refreshing).

Navigating to new pages that are not server hits (but client only) is just fine and works great. It's the server that sometimes doesn't call `preload`.

Sorry this is less helpful. I feel pretty blind as to what the problem is. It'll start working and I'll have no clue, and then the next moment it won't.

Potentially related bugs: #554, #415, #589, #586, #588, #587, and #555.

**Comment by neoel** [comment]
Is this with svelte.v3 & sapper alpha? I seem to be having the same issues there at least. although it is very consistently not being called on the server. 

Put a [sample video online](https://youtu.be/26t0jFx4iBw).
Here's a [REPL link](https://www.youtube.com/redirect?q=https%3A%2F%2Fv3.svelte.technology%2Frepl%3Fversion%3D3.0.0-beta.10%26gist%3Da99cdc5a270f3f5acac20e083d079dae&v=26t0jFx4iBw&event=video_description&redir_token=op9l4sMg-tFbxwBpHxN6Cj-ip9x8MTU1MjA1NDIzMUAxNTUxOTY3ODMx)

**Comment by arxpoetica** [comment]
@neoel are you using preprocessors anywhere?

**Comment by neoel** [comment]
@arxpoetica Yeah, I am using svelte-preprocess. For loading scss styles. I've tried only passing the styles prop in the preprocess object . 
```js
// ...
preprocess: { style: preprocess().style }
}
```

But that didn't seem to influence it.

**Comment by neoel** [comment]
Ah, I've now completely removed it. And it does not trigger the bug. So svelte-preprocess has something to do with it then, any clue what changes cause this. (I'm not familiar with the innards here)

**Comment by arxpoetica** [comment]
I created a repro: https://github.com/arxpoetica/gah

**Comment by Conduitry** [comment]
Quick summary of findings: The `has_preload` function (that's used in generating the manifest that will determine whether to call `preload` on server renders) does not and cannot know about any preprocessors you may want to run on your code and it attempts to compile it as-is. This fails with things with e.g. invalid styles which need preprocessing, and when compilation fails Sapper assumes there's no `preload` in the component.

A possible solution (which would only work with `<style>`s that need preprocessing, which I imagine would be the majority of the cases this would show up) is to just nuke any `<style>` tags before `has_preload` sends the component to the compiler, since those aren't going to affect whether there's a `preload` anyway.

**Comment by arxpoetica** [comment]
PR https://github.com/sveltejs/sapper/pull/597

**Comment by Conduitry** [comment]
Closing this - _should_ be fixed in alpha 12. 🤞

**Comment by YamiteruXYZ** [comment]
preload still doesn't get called

**Comment by arxpoetica** [comment]
@YamiteruXYZ can you confirm Sapper and Svelte versions?
