### ISSUE TITLE
Linked components don't bind `bind:this` correctly

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#711]
I tried to reproduce this in a codesandbox but technical restrictions prevent it. Essentially:

If you have a sapper project, and you have a component in another module, and you use `npm link` to develop the component locally, any `bind:this` references in the linked module don't get bound.

So for example:

```html
<button bind:this={button}>click me</buttton>

Button is: {button}

<script>
export let button
</script>
```

If you were to install the component as a node module, or have it locally, you would see:

Button is [Object HtmlElement] or similar.

If the component is in an `npm link`ed module, you will see:

Button is

Since the reference is null/empty.

This makes local development/testing of components/component libraries very difficult

**Comment by Conduitry** [comment]
When things like this have happened before, it's that the svelte internals are getting bundled twice. Either `pkg.svelte` was incorrectly specified in the imported component (for Rollup), or the build config didn't add `svelte` to `resolve.mainFields` in the consuming project (for webpack).

I'm assuming that stuff is set correctly? It would be weird if this were being affected by the package being symlinked though, I'm not sure why that would be.

**Comment by mrkishi** [comment]
The thing is that even with `pkg.svelte` set, if you have `svelte` in your symlinked component's `node_modules` folder, node's module resolution says you end up with two different versions of svelte.

If this was plain node, `--preserve-symlinks` could take care of it (although [it comes with a bunch of caveats](https://nodejs.org/api/cli.html#cli_preserve_symlinks)), but since we're bundling, it depends on how rollup/webpack _and_ their plugins (eg. rollup-plugin-node-resolve) deal with symlinks...

**Comment by Conduitry** [comment]
I don't know about webpack, but I'm thinking it might make sense for `rollup-plugin-svelte` to find the main, root copy of `svelte`, and to manually resolve all imports from `svelte/...` that it finds to this one copy, before `rollup-plugin-node-resolve` gets a chance to.

**Comment by Conduitry** [comment]
Closing this, this is not directly related to Sapper, and is going to be solved in the bundler plugin.
