### ISSUE TITLE
Support JSX

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [sveltejs/sapper#73]
Would it be possible to provide a mechanism for writing templates in JSX rather than svelte? I guess it would be a welcome addition and could potentially address the barrier to entry for people coming from a react background.

**Comment by Crisfole** [comment]
I'm not @Rich but I'm guessing this is a no. Sapper uses svelte because svelte provides all the hot reloading, code splitting, compilation tools for free. To support jsx there'd need to be a wrapper that provided the same compiler interface as svelte to jsx components.

I'm think sapper is (purposely) coupled very heavily to svelte.

**Comment by Conduitry** [comment]
Yeah, Sapper is, by its very nature, Next.js but for Svelte. If you want Next.js but for Svelte but for React, just use Next.js 😝

**Comment by Crisfole** [comment]
I will add that svelte is stupidly easy to learn.

**Comment by Rich-Harris** [comment]
Closing for the reasons outlined above — this would defeat the object of Sapper
