### ISSUE TITLE
Document --legacy 

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#739]
https://github.com/sveltejs/sapper/issues/280

**Comment by kylecordes** [comment]
Here is an alternative idea. Rather than document this option, consider removing the option. Instead a "production" build would automatically include differential bundling. In the future when there are almost no browsers left that need the old code, an option could be introduced to `--skip-legacy`.

Or maybe by then the ES5 output could be removed, and no option (thus no documentation other than "**of course** Sapper does differential bundling, you need not even ask") would ever be needed.

**Comment by sw-yx** [comment]
@Conduitry  - may i ask why this was transferred over from the docs repo? 

i'm going to open up a WIP PR for this one and we can discuss documenting there

**Comment by Conduitry** [comment]
This is the docs repo now as well. <https://sapper.svelte.dev/> lives in the site directory of this repo. Since Sapper was updated for Svelte 3, the other repo is for what's at <https://sapper-legacy.svelte.dev/>.

**Comment by sw-yx** [comment]
oh.. lol ok

**Comment by sw-yx** [comment]
ok i've moved over the PR!

**Comment by diverent2** [comment]
Here's another idea: How about using `--support-legacy` instead?
IMO this clarifies that it's meant for browser support without getting too verbose or causing confusion.

Just an idea though :)

**Comment by sw-yx** [comment]
please open a new issue, i gave up on my pr
