### ISSUE TITLE
Array of readable and writable stores

### ISSUE THREAD

**Issue by NaveenaSreenivasan** [sveltejs/sapper#786]
Is it possible to declare an array of readable/ writable store in stores.js and import in any .svlete file ?

import { writable } from 'svelte/store';

1. _**export const count = writable(0);** _ 
 The above count just a variable that holds the number value.

2. _**export var myArr = writable(["aaa","bbb","ccc","ddd","eee"]);**_
 I tried this to declare array but nothing works out when i import in index.svelte file. 

Can someone guide me in this issue ?

**Comment by antony** [comment]
@NaveenaSreenivasan This is a question and is better asked in the [chat room](https://svelte.dev/chat) or on [stackoverflow](https://stackoverflow.com/questions/tagged/svelte).

Stores can hold any value, so your exported store is just holding an array value instead of a primitive value like `0`. You are only exporting a single store, not an array of stores.

```
export const myStores = writable(["aaa","bbb","ccc","ddd","eee"])
```

We will be more than happy to help you further if you produce a [https://svelte.dev/repl/hello-world?version=3.6.3](REPL) showing your problem and expectation, and come and chat to us in the chat.

**Comment by NaveenaSreenivasan** [comment]
I am not able to work in [https://svelte.dev/repl/hello-world](url) right now. There is some issue with compiler in the site. Please check it.
<img width="1676" alt="Screenshot 2019-07-03 at 2 58 51 PM" src="https://user-images.githubusercontent.com/38436515/60580819-5ef73480-9da3-11e9-98d9-c37455dcc819.png">

**Comment by antony** [comment]
Yes, google are having some issues right now. See https://github.com/sveltejs/svelte/issues/3154

You can still come and talk in the discord though and we will help.

**Comment by NaveenaSreenivasan** [comment]
Got the solution in https://svelte.dev/chat. Hence closing this !
