### ISSUE TITLE
Sharing Data Between Pages in Sapper

### ISSUE THREAD

**Issue by nickreese** [sveltejs/sapper#797]
First, having come from building 5,000 page sites on Gatsby, I’m really liking what I’m seeing with Sapper. It feels like a breath of fresh air. Data flow is pretty simple and the site that it exported is substantially smaller.

That said, I’ve hit a roadblock on how to build something that seems deceivingly simple: Breadcrumbs. 

It Gatsby it is pretty easy to query data about a page’s “parent” to get the title tag / permalink. With Sapper, I can’t seem to figure out how to get the title tag of the parent page. 

I’ve played with using a custom store where each page when it get’s it’s data it pushes it’s permalink and title tag to an array so other pages can access it... then I'd write a little module to parse the URL and find the pages "before" the current page in the URL as the breadcrumbs... but this “feels” wrong. 

Can anyone point me in the right direction on the correct or most common way for pages to share data between each other?

How is this accomplished in Sapper?

**Comment by antony** [comment]
Hi Nick,

The correct place to get help is in the Sapper discord channel, rather than raising an issue.

However, in brief, you should share data using stores, and there is a page store which is exported from the `@sapper/app` module within your application, which contains path, params, and query data.

Please feel free to join us on discord for a more detailed explanation.
