### ISSUE TITLE
What are the Supported Browsers?

### ISSUE THREAD

**Issue by benwinding** [sveltejs/sapper#876]
What's the intended browser compatibility of **sapper**? Can't find it written anywhere...

Would be nice if we could have a chart like this:

![01-svg-support-table](https://user-images.githubusercontent.com/11782590/64391882-91662c00-d089-11e9-8eb8-16b3fc0aeb69.jpg)

**Comment by Wolfr** [comment]
You use Sapper to write code that has its own browser compatibility? As I understand it Sapper's browser compatibility is not relevant as it is the tool you use to help you write the code and itself it doesn't output any code that has browser compatibility issues.

**Comment by kylecordes** [comment]
Browser support is definitely an important question. At some point a while back a fresh default Sapper app did not work in IE 11. There is been considerable discussion of the merits of such support.

(My opinion is split: it is both a moral abomination and a business necessity. ;-) )

Support would mean that if you use the swath of available features in Sapper and Svelte, the default tooling emits any necessary polyfills, compile target settings, etc. to work correctly across the set of supported browsers. Out of the box. Although this is on one hand a bunch of annoying work, it is the bar that is set by the current crop of popular frameworks.

**Comment by Wolfr** [comment]
Right, thanks for the info @kylecordes , I am new to Sapper. I wanted to make some prototypes but some of my clients want to support IE11.

So it's good to know that the default bundle setup might not specifically work in IE11 and you shouldn't use Sapper if you want to support legacy browsers.

**Comment by benwinding** [comment]
So I was using the `fetch()` api and was hoping it would be transpired to work on older platforms, but it wasn't...

Is there a way to target older browsers too? Would **babeljs** help here? Incorporated into Webpack or something?

**Comment by fvsch** [comment]
@benwinding:

You need a bit more than transpiling to make fetch happen in IE. Fetch is not syntactic sugar, it's an API provided by the platform (a web browser). You can serve IE or all browsers a script that polyfills the Fetch API using XMLHttpRequest and Promises, such as https://www.npmjs.com/package/whatwg-fetch

As their docs say, to support IE you will also need a Promise polyfill. Not sure if Babel handles this.

> Would babeljs help here?

Yes and no. It's not always clear what Babel handles through a plugin, or through something like `babel-preset-env` which plucks polyfills from the `core-js` package. In my experience the world of making "modern JS" compatible with "old browsers" through "polyfills" requires a lot of reading and head-scratching if it's not 100% set up for you (and it can't be 100% set up for you anyway because polyfilling _all the things_ would add megabytes to your bundles, so most tools give you some reasonable basics and then you have to add more polyfills that you actually need). So good luck on your journey, and you can look at:

- https://babeljs.io/docs/en/babel-preset-env
- https://polyfill.io/
