### ISSUE TITLE
[Request] Document CLI flag configuration options

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/sapper#885]
**Is your feature request related to a problem? Please describe.**

there is no place on the docs to document notes for each of the CLI flags. there are places for `sapper build` and `sapper export` but none for `sapper dev` and no good way to document flags that are just common to all of them. this argues for a distinct "CLI API" section.

Example issues that could be addressed:

- `--ext` flag: https://github.com/sveltejs/sapper/issues/827
- `--legacy`: https://github.com/sveltejs/sapper/issues/739
- `ignore`: https://github.com/sveltejs/sapper/issues/736
- `--entry`

**Describe the solution you'd like**

this argues for a distinct "CLI API" section.

**Describe alternatives you've considered**

misery

**How important is this feature to you?**
low importance but easy to do

**Comment by pngwn** [comment]
I think this is a good idea, we don't have a great place to document these currently, and the CLI args have grown somewhat recently.

I think a "CLI API" section with links from various sections down to the CLI docs makes the most sense (so that users reading specific sections don't miss out on anything if they aren't in the habit of `ctrl-f`-ing).

I think it makes sense to have these grouped in a section but am wary of people who just read the 'relevant' not realising that the solution to their problem is a CLI argument that they may not even know exists. A link in the relevant section may go some way to solving this.

- A link in the "Exporting" section to the CLI args (with a quick note about `--entry`).
- A link in the "Routing - Pages" section to the CLI args (with a quick note about `--ext`)

`legacy` doesn't really have a natural home to link from but we should add details about browser compatibility (or at least feature compatibility) somewhere in the Sapper docs. This is an important point for many people and comes up relatively often.

`ignore` isn't a CLI argument, so I'm not sure what should happen with it.

**Comment by sw-yx** [comment]
@pngwn please, you look
![image](https://user-images.githubusercontent.com/6764957/64629827-ec698d00-d3c1-11e9-8c37-b65cc730b59d.png)
