### ISSUE TITLE
query argument of preload function is empty in production mode

### ISSUE THREAD

**Issue by efattal** [sveltejs/sapper#914]
I added a preload function to my routes/xyz/index.svelte and I open /xyz?foo=1. I can only get query.foo in dev mode but not in production mode. Is that normal?

```
<script context="module">
    export async function preload({params, query}) {
        //Dev mode: query.foo == 1 
       // Production mode: query.foo === undefined
    }
</script>
```

**Comment by Conduitry** [comment]
I'm not seeing this. Do you have a reproduction?

**Comment by efattal** [comment]
Thanks for helping.

Look at this simple example : https://github.com/efattal/github-issue-914/blob/master/src/routes/about.svelte
It works fine in dev mode but not in production mode (https://github-issue-914.efattal.now.sh/about?foo=1)

**Comment by Conduitry** [comment]
Query parameters don't work on the server side for exported sites, because there's a single file that's returned for all requests to the same path, regardless of query string. When the site was crawled, it the link was to `/about` with no query parameters, so that's what was saved to `.../about/index.html`. If you navigate to a different page, and then use the browser's back button to return to `/about?foo=1` using client-side navigation, you'll see that it is now set properly.

In order for query parameters to work with server-side rendering, you'll need to use a host that can run the Node server Sapper generates, which Now currently cannot do.

**Comment by efattal** [comment]
Thanks a lot for this complete answer.
