### ISSUE TITLE
! zlib: unexpected end of file

### ISSUE THREAD

**Issue by jet10000** [sveltejs/sapper#924]
```
npx degit "sveltejs/sapper-template#rollup" my-app
npx: installed 33 in 20.401s
! zlib: unexpected end of file

```

Windows7,  node v10.16.3, npm 6.9.0

I run `npm cache clean --force`, but still have this problem, and I found the my-app folder is empty.

-------------
But I can clone webpack's
```
npx degit "sveltejs/sapper-template#webpack" my-app
npx: installed 33 in 13.577s
> cloned sveltejs/sapper-template#webpack to my-app
```

**Comment by Conduitry** [comment]
I haven't seen this reported before, and it's not a bug in Sapper. It wouldn't surprise me if this were a network issue or a dropped connection, especially given that it's taking npx 20 seconds to download degit. If you're having trouble with degit, you can just download a zip of the appropriate branch.

**Comment by RuAnDe** [comment]
@Conduitry 
Sorry my bad english.

Just in case, I’ll leave a decision suddenly who else comes across. There was the same problem. npm cache clean --force will not help because the broken one is not the npm cache, but the archive downloaded by degit. Since degit is trying to use the cache, it does not pump it. It is solved by deleting the degit folder which in linux is located on the $HOME/.degit path. Or you can delete the cache exactly svelte ~/.degit/github/sveltejs.

**Comment by rohitsg** [comment]
deleting  $HOME/.degit folder works.
