### ISSUE TITLE
ssr: json instead of html

### ISSUE THREAD

**Issue by igolkotek** [sveltejs/sapper#933]
A weird situation.
I make a new sapper project setup with `npx degit "sveltejs/sapper-template#rollup"`.
Just for test make copies of `blog/[slug].svelte` and `blog/[slug].json.js` files.
As I have my API, I change filename `blog/[slug].json.js` to `blog/[slug].js` and return dumb json value:

> export function get(req, res, next) {
    const {slug} = req.params;
    res.writeHead(200, {
        'Content-Type': 'application/json'
    });
    const content = {name: slug, details: slug};
    res.end(JSON.stringify(content));
}

**Expected behavior**
Html page according to template.html both in client and ssr requests.

**In fact the result is**
raw json data returned.

**How to get correct web page again**
Just return file name as it was initially: from `blog/[slug].js` to initial `blog/[slug].json.js` .

**Comment by Conduitry** [comment]
If I'm understanding what you're saying correctly, this isn't a bug. `.js` files are treated as server routes, and `.svelte` files are treated as page routes. In both cases, that file extension is removed to get the actual url. When you have `blog/[slug].svelte` and `blog/[slug].js`, you have two routes with the same url (`blog/[slug]`), and one has to take precedence.

**Comment by igolkotek** [comment]
Not exactly.
According to documentaion: "Server routes are modules written in **.js** files".
In fact it looks like it should be "Server routes are modules written in **.json.js** files"

**Comment by Conduitry** [comment]
Only if you want `.json` to be in the URL. You can have server routes with whatever paths you want, that return whatever mime type you want.

**Comment by igolkotek** [comment]
Yes, I thought the same way. 
But in fact I got a raw json response instead of html page rendered by SSR with [slug].js file.
Just because of the absence of this .json.js  extension in file name.

**Comment by pngwn** [comment]
I think there is some misunderstanding here. 

`.js` extensions: express-like server routes. If you make a server request to this endpoint you will get whatever is in this `js` file.
`.svelte` extensions: actual pages that get returned when you navigate to a certain route. This will not be returned when making server requests to the endpoint.

For server routes, the `.js` gets cut off when it is compiled leaving you with `blog/[slug].json`. Since this content is a JSON file the endpoint should be something like `blog/my-blog-post.json`. If you want an endpoint without an extension name then you are free to do so (by calling it `blog/[slug].js`, without the `.json`) but this would need to match whatever is being requested on the server. Likewise, if you wanted a *different* extension name, that would also be fine (by calling it `blog/[slug].fabuloso.js` which would result in an endpoint like: `blog/[slug].fabuloso`).

These extensions can be whatever you want as long as that endpoint is matched in the server route itself. 

This isn't a bug but if there is still some confusion please come to the discord chat and we'll be happy to explain it further.
